### ISSUE TITLE
[Request] Objects not lockable within x distance of towns/territories/stores

### ISSUE THREAD

**Issue by l0dac** [A3Wasteland/ArmA3_Wasteland.Altis#168]
We have been dealing with many users placing objects within towns, capture points, and stores which at times is causing mass chaos for us to go in and clean out. 

It'd be nice to have a configurable value not allowing objects to be locked within a desired distance.

**Comment by LouDnl** [comment]
Here's what I cherry picked of someone elses GitHub. I rewrote the disallowedLocations.sqf (with code from AgentRev that I reused) to use the mission.sqm markers.
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/8d6c2d87d2e9eedf09b452847d3b93bff5ebcfdc
