### ISSUE TITLE
Headless client support

### ISSUE THREAD

**Issue by nward** [A3Wasteland/ArmA3_Wasteland.Altis#174]
dwarden posted in the Skype group that there's new headless client functionality coming soon to A3.

This lets us offload scripting tasks to HC, along with the usual AI things. I'm pretty keen to get this implemented - I'm happy to work on this, dropping this issue here so if anyone else is interested we can collaborate.

Also, HC support for linux!

https://community.bistudio.com/wiki/Arma_3_Headless_Client

**Comment by AgentRev** [comment]
Object saving successfully deferred to headless client in v1.2 beta: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/1bc4acfa933b247e6a7c2955e7cce3e0301709f3
