### ISSUE TITLE
Darter backpack is not saved

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#208]
I have players complaining about the darter not loading back in after logging out and back in.
They have the darter on their back when logging out, player file is saved.
Player save shows: Backpack="I_UAV_01_backpack_F"

After they log back in the darter is gone and they have a normal backpack again.
Player save shows: Backpack="B_AssaultPack_rgr"

How can I fix this?

**Comment by LouDnl** [comment]
Ok so i'm not the best scripter here and am actually just pretending to do shit haha.

So make fun of me if you want :P

Would that be fixable with changing line 67 to the following? Or would that mess up the whole script?

if ((_value isKindOf "Weapon_Bag_Base") && (_value !isKindOf "B_UAV_01_backpack_F")) then

---

Van: Agent Revolution notifications@github.com
Verzonden: maandag 17 november 2014 13:15
Aan: A3Wasteland/ArmA3_Wasteland.Altis
CC:
Onderwerp: Re: [ArmA3_Wasteland.Altis] Darter backpack is not saved (#208)

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/b385304e551d3561eef7c7713b2cd96baf764edd/persistence/players/c_applyPlayerData.sqf#L67-L74

I guess that's an unwanted side effect of trying to stop people messing with static weapon turrets

## 

Reply to this email directly or view it on GitHubhttps://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/208#issuecomment-63296594.

## 

This message has been scanned for viruses and dangerous content by
E.F.A. Projecthttp://www.efa-project.org/, and is believed to be clean.

## 

This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by Tucan55** [comment]
Sorry to rain on your parade but the problem persits

**Comment by LouDnl** [comment]
Are you using Profilenamespace saving, iniDB, extDB or node.js?

**Comment by Tucan55** [comment]
I am afraid i have no idea what you mean?
Do i need to change some of the files to make it work?
