### ISSUE TITLE
Stratis map maybe Altis also Players can't join Indy receiving data

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Altis#211]
I have the latest files, seems the bug can't join INDY has come back. I'll keep a check on it to see how many times it happens. You click join in the lobby screen goes to receiving data and stay there until server is restarted.

**Comment by LouDnl** [comment]
?I'm sorry, didn't mean to agitate you. Just showing interest :)

I'll leave you to your hard work.

---

Van: Agent Revolution notifications@github.com
Verzonden: dinsdag 25 november 2014 15:55
Aan: A3Wasteland/ArmA3_Wasteland.Altis
CC: 
Onderwerp: Re: [ArmA3_Wasteland.Altis] Stratis map maybe Altis also Players can't join Indy receiving data (#211)

Do not ask me for ETAs.

## 

Reply to this email directly or view it on GitHubhttps://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/211#issuecomment-64410980.

## 

This message has been scanned for viruses and dangerous content by
E.F.A. Projecthttp://www.efa-project.org/, and is believed to be clean.

## 

This message has been scanned by E.F.A. Project and is believed to be clean.
