### ISSUE TITLE
Server cleanup

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#233]
Rev,

You once stated that the server clean up script cleans up dead bodies and blown up vehicles but leaves items like weapons and backpacks and such be.
What I can see on my server is that the more missions get cleaned up and the more players die the object count goes up. The higher the object count goes, the lower the fps drops.
Is there a way to clean these objects say about 15~30 minutes after they are dropped?
This way the server doesn't get "littered" with objects.

**Comment by lenymo093** [comment]
What about the repair kits, water bottles, and food containers. Wouldn't these count as PhysX objects?

**Comment by AgentRev** [comment]
Yeah they are PhysX objects, if you use the HC normally this isn't a problem.

**Comment by AgentRev** [comment]
Also, building loot is cleaned every 30 mins.
