### ISSUE TITLE
Scoreboard showing player with 0 kills in top 10

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#240]
Number 7 doesn't have any kills but still shows in the scoreboard.
What happens here is that someone with a lot of deaths also gets scoreboard points?
I mentioned this before and you wanted a screenshot.

http://i.imgur.com/u8A3gbR.jpg

**Comment by LouDnl** [comment]
Got any clue why this is Rev?

**Comment by AgentRev** [comment]
2 player kills - 2 teamkills = 0, I guess I forgot to take TKs into account in the sorting algorithm

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/d6b6a10486e15f1d64bb4feb6630408ed4b5f8c1
