### ISSUE TITLE
Dissapearing spawnbeacons

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#242]
Spawnbeacons don't always load up in the spawn menu.
When you're in a group and you have more then 1 beacon they don't all show.
And sometimes none show.

**Comment by AgentRev** [comment]
Can you confirm if the spawn button says "Loading..." or "Spawn" when none show?

**Comment by LouDnl** [comment]
I will check this tonight.

**Comment by LouDnl** [comment]
Could it be that they are reset on a server reset? I placed one last night in a secure place for testing and it is now gone in the database. Will check this tonight aswell.

**Comment by LouDnl** [comment]
Allright, so I was in a group of 5 people. 2 of us place 3 beacons, 1 placed 2 beacons and 1 placed 1 beacon. I pressed escape and clicked respawn. In the respawn dialog after the 'loading' part dissapeard only 3 beacons showed. My own beacons did not show and I saw 1 beacon of 3 other people. That cannot be right :)
I will test their persistence at next restart in 2 hours.

**Comment by LouDnl** [comment]
When leaving the group, going back to the lobby and respawning I had no spawnbeacons. Though all are in place :)
Disconnecting and reconnecting to the server did not work.
They do however save in the database.

**Comment by AgentRev** [comment]
You still haven't told me the side you were playing on. This is very important.

**Comment by LouDnl** [comment]
Drumroll..... Independant :)

**Comment by LouDnl** [comment]
All placed spawn beacons were gone after the restart.

**Comment by LouDnl** [comment]
Spawnbeacons seem to be dissapearing after each restart. So we have two issues.
1. Placed spawn beacons do not always show in the respawn dialog.
2. Spawn beacons dissapear from database after a restart.

Don't know if related, but after the restart of 3 am there was this error in the rpt which hasn't shown before:
 3:01:34 "A3Wasteland - world persistence loaded 507 objects from extDB"
 3:01:34 Error in expression <[(_vars select _forEachIndex) select 1, _x];
} forEach _x;

_vehicles pushBack _>
 3:01:34   Error position: <_x];
} forEach _x;

_vehicles pushBack _>
 3:01:34   Error Undefined variable in expression: _x
 3:01:34 File mpmissions\ArmA3_Wasteland_v1_NLU.Altis\persistence\server\world\extDB\getVehicles.sqf, line 57

**Comment by LouDnl** [comment]
I recently set A3W_extDB_SaveUnlockedObjects to 0 because I had too many objects in the server. I put this back to 1 now and will test the persistence of beacons tonight.

**Comment by LouDnl** [comment]
With A3W_extDB_SaveUnlockedObjects set to 1 the spawn beacons were still there after one restart. Will report tomorrow after two more restarts.

**Comment by AgentRev** [comment]
Yeah this is a design flaw I identified some time ago, it's already fixed for the next DB update

**Comment by LouDnl** [comment]
So that only leaves the bug for spawn beacons not being able to spawn on?

**Comment by LouDnl** [comment]
Is persistence of beacons fixed in 1.1 so that A3W_extDB_SaveUnlockedObjects set to 1 is no longer needed?
Beacons still do not always show when you place them and respawn. Last night I place 2 beacons and respawned 15 minutes after. I could only see 1 of them in the spawn menu.

**Comment by LouDnl** [comment]
Anyone else experiencing this problem? If not it could be to do with low server cps?

**Comment by LouDnl** [comment]
This seems fixed.
