### ISSUE TITLE
extDB: Mission vehicles

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#243]
Force save on mission vehicles isn't there on capture. After a server restart the force save option is available.
My guess is that the missionvehicle variable isn't broadcast after capture but is after the saved vehicle is loaded in after a restart?

**Comment by AgentRev** [comment]
You're correct.

**Comment by LouDnl** [comment]
Allright :) is it intentional?

**Comment by AgentRev** [comment]
Of course not lol

**Comment by AgentRev** [comment]
218acfee7061f694ad7d849c3131b2f5ab5cdd3a

**Comment by LouDnl** [comment]
Thanks for the fix Rev.
