### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#246]
When you buy rockets from the shop (any rocket) and when wearing any gear with enough space the rockets goes in this gear (clothes, vest). But when picking up rockets you can only put it in your backpack.

Second if you have rockets in your clothes or vest and if you want to buy a launcher, the launcher doesnt get bought but the shop says buy succesful. You dont lose any money. As soon as you take out the rocket from your clothes and try to buy again it works fine.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/72f4b30c14b7edf2eeb8dcbd85a7c45f628a9718

**Comment by LouDnl** [comment]
Thanks Rev. Does this fix the second bug too?

**Comment by AgentRev** [comment]
The second bug is caused by the first one, you already know the answer.

**Comment by LouDnl** [comment]
<3
