### ISSUE TITLE
extDB: Headlessclient

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#253]
For some reason the headlessclient takes up a player slot. When I put the serer on 50 slots only 49 players can join. So I now run my server on 51 slots lol ;)
I've posted about this on the Bohemia forums and in their Skype group but cannot get a good answer.
The only answer I'm getting is that it's mission dependent and that with normal configuration it shouldn't take up a player slot.
When I compare the headlessclient entry with the Biki it's exactly the same so I do not get it.
Is it normal for the HC to take up a player slot in Wasteland?

**Comment by AgentRev** [comment]
Yes, the headless client takes a player slot, this is normal, it has always been like that, and most likely will always be.

**Comment by AgentRev** [comment]
The people that told you this is mission-dependent are mixing up mission slot from server slot.

**Comment by LouDnl** [comment]
Allright thanks Rev.


Verstuurd vanaf mijn iPhone

Op 12 jan. 2015 om 16:29 heeft Agent Revolution <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The people that told you this is mission-dependent are mixing up mission slot from server slot.

-
Reply to this email directly or view it on GitHub<https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/253#issuecomment-69587225>.

--
This message has been scanned for viruses and dangerous content by
E.F.A. Project<http://www.efa-project.org>, and is believed to be clean.


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by AgentRev** [comment]
By the way, do you think you could always reply via the Github website instead of email? It adds a lot of garbage to your comments.

**Comment by LouDnl** [comment]
Sure :) And I can ofcourse remove the garbage ;)

**Comment by AgentRev** [comment]
You can also erase all the existing text from your email reply box before starting to type your message, it prevents garbage.
