### ISSUE TITLE
ATM icons drawn on map even when ATMs are disabled 

### ISSUE THREAD

**Issue by micovery** [A3Wasteland/ArmA3_Wasteland.Altis#256]
I know you delete the map ATMs when ATMs are disabled ... that seems a bit overboard.

**Comment by LouDnl** [comment]
Can you enable ATMs and disable markers?

**Comment by micovery** [comment]
Yeah, see this change.  
https://github.com/A3Armory/ArmA3_Wasteland.Altis/commit/75478692e0b35228b4f1ee6fef2b37d5defe7775

Just make a new config variable.

**Comment by AgentRev** [comment]
Delete the map ATMs when ATMs are disabled = intended, don't see why that would be overboard
ATM icons drawn on map even when ATMs are disabled = I don't see any icons when disabled...

**Comment by micovery** [comment]
Closing this, since it's as-designed.
