### ISSUE TITLE
A3W_extDB_SaveUnlockedObjects

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#263]
With A3W_extDB_SaveUnlockedObjects set to 1 vehicles that are destroyed long before a server restart somehow get restored after a server restart.

**Comment by AgentRev** [comment]
A3W_extDB_SaveUnlockedObjects has absolutely nothing to do with vehicles at all...

**Comment by LouDnl** [comment]
Well I get that, it doesn't say objects for nothing. But this is still something that happens though.

**Comment by AgentRev** [comment]
Then it has nothing to do with that setting, because it's completely separate from all vehicle scripts.

**Comment by LouDnl** [comment]
But it only happens after this setting is set to 1.

**Comment by LouDnl** [comment]
I've set it to 0 now and will let you know later today.

**Comment by LouDnl** [comment]
You are right sorry. Have it off now and it still happens. Want me to add a new issue or change this one?

**Comment by AgentRev** [comment]
I don't even know how to reproduce it, I've never seen it happen. As long as vehicleSetup is called right after the vehicle's creation, normally it instantly gets deleted from the DB on death.

**Comment by LouDnl** [comment]
Yea I know, I wouldn't know how to reproduce it also. I've even had vehicles that were destroyed half an hout at least before a restart come back in one piece after a restart.

**Comment by AgentRev** [comment]
Well you need to determine if the database is properly deleting the vehicle by destroying many of them manually and checking if the ID was removed from the database just after.

**Comment by LouDnl** [comment]
Will do that on test server soon.

**Comment by LouDnl** [comment]
Seems to be fixed. Not heard anyone about destroyed vehicles spawning back in after a restart.
