### ISSUE TITLE
Thermals and Radar

### ISSUE THREAD

**Issue by Classifed787** [A3Wasteland/ArmA3_Wasteland.Altis#264]
I noticed in the new version Thermals and some Radar have been disabled. Is there an option for us to turn these back on, and if so where might that be located?

**Comment by Classifed787** [comment]
Found it, so I answered my own question.

**Comment by LouDnl** [comment]
Where did you change this? I know of the thermals but not of the radar.

**Comment by AgentRev** [comment]
I never disabled any radar, why do people think I have anything to do with it, there is no such option.

**Comment by LouDnl** [comment]
I thought that was the case as the radars in some helicopters were disabled when the helicopters dlc came out. But since Classifed787 said he found it I was interested :)

**Comment by Classifed787** [comment]
Yeah, sorry about that. I realized that shortly after I posted it. My apologies. I didn't find the location of where the radar for certain helicopters were disabled, but I did find the thermals location. Still looking for the radar location just to clarify, sorry about that again guys.

**Comment by OWReaper** [comment]
ok where was the thermals on/off switch=code still noob here lol

**Comment by Classifed787** [comment]
Sorry, I never received the notification for your comment.
server\functions\vehicleSetup.sqf
Open that up and scroll down to about line 24 and you should see it.
