### ISSUE TITLE
Bug message when depositing/removing cash from money stash

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#267]
When I deposit or remove cash from a money stash I get this message: WarchestRefrest - This Shouldnt Happen
This message resides in client\items\warchest\refresh.sqf. But it's not a warchest, it's a normal crate.
Money does get saved though.

**Comment by AgentRev** [comment]
Bug probably fixed, reopen if it occurs again
