### ISSUE TITLE
Unable to move autonomous static weapons

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#268]
Neither can them be disassembled.

**Comment by AgentRev** [comment]
I can move them no problem...

**Comment by LouDnl** [comment]
Same here no problem. And they shouldn't be dissasembled. Rev blocked this.

**Comment by OWReaper** [comment]
I am unable to move the autonomous static weapons now that they have been disabled from been disassembled either. does not give me an option to move or load into vehicles. but then again was not able to move them prior to fix unless they were disassembled before.

**Comment by Jermin** [comment]
There is only an option for disassembling. But there isn't any move commands.

When I press on the disassemble button, I receive a warning saying:

"You are not allowed to disassemble weapons. Use the "Move this object" option instead.
