### ISSUE TITLE
Camonet unlockable after disabling building loots

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#269]
Camonets bought from general stores are not lockable after disabling building loots

By the way, is it possible to add large water barrels and food bags into general stores? They also stop spawning after disabling building loots.

**Comment by AgentRev** [comment]
Camonets ARE lockable and have never been at all.

**Comment by Jermin** [comment]
I mean if you don't lock them, they will not be saved between restarts.

**Comment by LouDnl** [comment]
Thats normal?


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by LouDnl** [comment]
Jermin,

If you want to add foodsacks and waterbarrels to shop make sure you add this to your spawnstoreobject.sqf:
https://github.com/LouDnl/ArmA3_Wasteland.Altis/blob/NL-United/server/functions/spawnStoreObject.sqf#L203-L213

These lines for adding em to stores:
https://github.com/LouDnl/ArmA3_Wasteland.Altis/blob/NL-United/storeConfig.sqf#L571-L572

**Comment by Jermin** [comment]
Thanks!

**Comment by AgentRev** [comment]
Yes, camonets don't save. I don't consider it important enough to fix it.
