### ISSUE TITLE
Kicked for memory editing hack - New AH Commit

### ISSUE THREAD

**Issue by osuapoc** [A3Wasteland/ArmA3_Wasteland.Altis#270]
Updated our test server with the latest commits for JAN25, and at the same time added in the additional missions and controllers/processors from LouD's mission.  Upon joining my character was killed before even fully spawning in, as well as I was kicked shortly thereafter.

Here is the server log file for that instance:
http://pastebin.com/MJQZEGZb

Here's the client file for that same time:
http://pastebin.com/Xi1pGzvp

Here's the meat of it:
"pvar_requestPlayerData: [4,B Alpha 1-2:1 (Apoc) REMOTE,B Alpha 1-2:1 (Apoc) REMOTE]"
"ANTI-HACK: Apoc (76561197971991469) was detected for [memory editing] with the value [RscDisplayAVTerminal]"
"DEBUG ----- extDB ASync: Complete Time:0  Input String:addAntihackLog:1:Apoc:76561197971991469:memory editing:RscDisplayAVTerminal"

**Comment by JoSchaap** [comment]
fixed in latest commits
