### ISSUE TITLE
towed vehicles vanish when you un-tow them

### ISSUE THREAD

**Issue by Angrygargamel** [A3Wasteland/ArmA3_Wasteland.Altis#272]
some players on our server (1.1 extdb save variant) reported a bug where their towed vehicles vanished a few seconds after they un-towed them after driving a few miles...

so its just like: tow a vehicle to another vehicle on point a... drive 2miles to point b.... untow the vehicle... BAM.... its gone...

**Comment by McGrizzle67** [comment]
This happens to me as well.  A band-aid solution is to run back to where you originally hooked up the vehicle.  Most of the time it will be there.  Pain in the A but if you were towing a valuable vehicle its worth it to go back.

**Comment by JoSchaap** [comment]
have you monitored your server's performance when this occurs? because i cant seem to replicate it on my stratis server

**Comment by osuapoc** [comment]
We used to see this kind of behavior in A2 Overpoch when the server was running slow. Oftentimes it could be prevented by getting into the vehicle as driver before hooking it up to tow.  Once we moved to a higher performance server the issue mostly disappeared I believe. 

-----Original Message-----

**Comment by JoSchaap** [comment]
This seems to be performance related, i've only managed to reproduce this on a home-hosted server that had 55 players on stratis while running at 1 or 2 fps... (according to it's admin)


If anyone manages to reproduce it on a server running proper fps (15+) feel free to reopen this
