### ISSUE TITLE
Screen-shaking bug

### ISSUE THREAD

**Issue by McGrizzle67** [A3Wasteland/ArmA3_Wasteland.Altis#273]
We are running a wasteland server where an unknown trigger causes every player's screen to shake every 2-3 seconds.  It makes shooting at range extremely difficult.  It clears up with a server reset only to return a short while later.  While this is happening any vehicle you approach will have its tires sink into the ground a little bit and has to be towed out to return to normal.

**Comment by LouDnl** [comment]
This is an arma 3 bug related to the 1.38 update. Not Wasteland related. Turn off camerashake in your server profile for now. 

--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by McGrizzle67** [comment]
Thanks for the quick response!  I'm filling in for our primary admin, do you know off the top where I might find said profile?

**Comment by McGrizzle67** [comment]
https://github.com/Beefaloaf/NANA_Wasteland.Altis

**Comment by LouDnl** [comment]
In your servers profile user dir not in the mission. 


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by McGrizzle67** [comment]
Thanks again Lou.  All we got was the mission file from our admin, but at least now we know what we need!
