### ISSUE TITLE
Missions Getting stuck

### ISSUE THREAD

**Issue by l3v1ath3n** [A3Wasteland/ArmA3_Wasteland.Altis#274]
Hi there, i have been noticing recently that missions indicators on the map are persistent even after the mission has been completed. I am seeing doubles on the map in some cases. Anyone seeing this?

**Comment by JoSchaap** [comment]
can't reproduce it, have you tried using an unmodified mission to make sure it isn't caused by edits?

**Comment by Beefaloaf** [comment]
This is no longer an issue.
