### ISSUE TITLE
Not really an Issue, just a question on merging wasteland files

### ISSUE THREAD

**Issue by Classifed787** [A3Wasteland/ArmA3_Wasteland.Altis#275]
I tried to add this as a question but couldn't get it to work. Sorry in advance. My question; is there an easier way of merging the new updated versions you come out with my features that I have added, than manually going through the whole thing and moving all my stuff back over to the new version.
I was thinking that there must be a way to merge my old version into the new version by using a program that might make it easier than using notepad++. 
Any advice would be helpful, cause missing that one semi-colon can be a real pain to track down.

**Comment by robertlewis** [comment]
Might want to look into Araxis Merge.

http://www.araxis.com/

If you don't want to pay for it, I'm sure you can find a cracked torrent. 

You can use it to merge folders and looking at what's changed in the files by comparing them.

**Comment by Beefaloaf** [comment]
Merging with powershell and notepad++ isn't that bad unless you have lots of conflicts.  I mean, it marks the conflicts nicely so you can find the issue.  There are tools however to help on the visual side of things.

http://www.gitguys.com/topics/merging-with-a-gui/

**Comment by LouDnl** [comment]
You can try meld merge too. Or hold you own separate branch where you manually add the commits like I do. 

--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by Classifed787** [comment]
Okay, thanks for the information guys. I will give those a shot. Right now I am just using Notepad++ and one of my admins who is going to school for programming told me about the addon for notepad++ which will do the compare for me. So that should make things easier too.
