### ISSUE TITLE
Store sell crates bouncing around after arma update

### ISSUE THREAD

**Issue by CRE4MPIE** [A3Wasteland/ArmA3_Wasteland.Altis#276]
I've seen a lot of the store crates move around or become inaccessible since the last update - I will try put an offset on the box spawn , but it appears the box sometimes spawns too close to the desk and flies around.

**Comment by LouDnl** [comment]
Rev implemented a fix for this a couple of days ago. Did you implement this?
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/0cf4c2e4d1b50503ccd60ef01e36b5ed169ddc6e


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by CRE4MPIE** [comment]
Negative ^_^;;; Will do so now ;>
