### ISSUE TITLE
Spawned Vehicles stuck in ground? 

### ISSUE THREAD

**Issue by l3v1ath3n** [A3Wasteland/ArmA3_Wasteland.Altis#277]
just recently we have been noticing that about 60% of the transports in wasteland are spawning with their wheels submerged. Has anyone run into this?

**Comment by AgentRev** [comment]
v1.38 shenanigans

**Comment by LouDnl** [comment]
It's an arma bug. Several feedback tracker issues already. 


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by l3v1ath3n** [comment]
thank you guys. i figured.  i will hang tight!
