### ISSUE TITLE
Bought empty ammo crates can't be accessed while under water

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#278]
When placed under water, the empty ammo crates sold at general stores doesn't have an inventory option. However, weapon cases provided by missions do.

**Comment by LouDnl** [comment]
I'm not getting the inventory option on all crates. Thought it was meant that way :)

**Comment by AgentRev** [comment]
That's an Arma 3 thing, unrelated to Wasteland, can't be changed afaik.
