### ISSUE TITLE
Vehicle Extra Inventory Saving (extDB)

### ISSUE THREAD

**Issue by Beefaloaf** [A3Wasteland/ArmA3_Wasteland.Altis#279]
Will there be any saving of the extra inventory space added by the already included R3F inventory?  It looks like the database already saves the normal inventory.

**Comment by AgentRev** [comment]
No. Those are completely different, the R3F inventory is much more complex.

**Comment by Beefaloaf** [comment]
Yeah it looks like a headache.  A container (vehicle) with a container (crate) full of items.

**Comment by AgentRev** [comment]
I mean, both can be saved to the same table, but it's restoring it that's a a pain the butt. For example, what happens if you have a quad inside the R3F inventory of an SUV, but the quad gets loaded from the DB first? It'd be a mess to handle

**Comment by Beefaloaf** [comment]
Hmm.  yeah, makes my brain hurt the more I think about it.  I'm thinking of a scenario where the vehicles/objects are tagged with a variable that indicates whether it's a "loaded" item or not.  If true it gets skipped during the load process, and loads later...   after the host object has loaded.

Lol, thanks for responding so fast.  Definitely kicks up some thoughts for me, not that I'm savvy enough with this language to pursue that yet.

**Comment by LouDnl** [comment]
Storeception


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by AgentRev** [comment]
Haha, thanks for the donation

**Comment by Beefaloaf** [comment]
lol, you welcome.  It wasn't fuel for this topic.  We've been running A3 and it's great.  Lots of work put into it for sure.

**Comment by nward** [comment]
I think this issue should stay open, and parked in some sort of "future" milestone as a feature request, perhaps someone goes an implements it.

I don't know how the extDB stuff works in detail, but I can't imagine it would be too difficult to sort things so they load from the DB in the correct order.
