### ISSUE TITLE
Feature request: Custom Load outs handled by the extdb

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#280]
Hi I'm wondering if this is being looked into and if not could it be? Or does anyone have any insight on how to make this a possibility? (Kinda like dayzCC's db was working this.) Any help would be appreciated.

**Comment by AgentRev** [comment]
Could you please be more precise?

**Comment by Beefaloaf** [comment]
I'm curious, why have loadout config in the database?  Is there a benefit to that over setting the loadouts via playerSetupGear.sqf and getDefaultClothing.sqf?

Would it be to handle a particular players loadout via some outside source?

**Comment by hobart666** [comment]
To be more precise, basically similar to your donators.sqf thing in the mission but in the database, Have a table named custom loadout where as you enter their PID and and gear items into the table and if they die, upon respawn they spawn in with the gear from the table per PID. like a donor thing.
 Crosire's dayzCC had this implemented if I remember correctly.

**Comment by hobart666** [comment]
Yes Beef that is correct, to handle a particular player's or players' loadout via sql.

**Comment by LouDnl** [comment]
I have this already, just not implemented :)


--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by hobart666** [comment]
Well LouD, I'm a pig from Guinea...

**Comment by LouDnl** [comment]
Creampie uses custom loadouts aswell. It would be fairly easy to refer the uid checks to an external file. 

--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by osuapoc** [comment]
I think the major difference is that they're wanting to have the loadouts managed via the SQL database and the extdb extension.  

I think both LouD and Creampie use an external SQF file with an array that is loaded with Donator UIDs.  

The advantage to the SQL call would be the ability to check for updated lists during server operation.  An enterprising person could also write some web code to have donators automatically added to the list from a store frontend.  

-----Original Message-----

**Comment by hobart666** [comment]
Boy I do wish I was that enterprising, I would have it done and posted for all.

**Comment by LouDnl** [comment]
Seeing as I'm not enterprising, having the uid's and the loadouts in an external file would be enough. This way you wouldn't have to update the mission every time you want to change something. 

--
This message has been scanned by E.F.A. Project and is believed to be clean.

**Comment by hobart666** [comment]
Between what  osuapoc and LouD say that is precisely why the sql db would be the way to go I dont mind using a donors file for the pid's alone and of course no one wants to add PID's to the mission every time someone is added that's a terribly messy way to go about it. so if we're using sql for the extdb it would make sense to have this handled by the db and some call (apologies, not a coder) to check the tables against a pid upon respawn after a death in game or when joining. I'm guessing have it only check to see if the player is a fresh spawn then give the loadout if the pid is in the db. plus being in the db it would make life a ton easier for the player that wants the loadout they can buy a loadout get what they want and say "yo admin/owner this is what I want for me loadout and one could just copy the table data from playersave to the custom loadout table bada-bing! but like I said I'm no coder. I'm totally inept it took me a week to edit the sql file to name the db jimbob_a3wasteland so I could create it on my website lol.
