### ISSUE TITLE
High winds affecting para dropping.

### ISSUE THREAD

**Issue by TastyDischarge** [A3Wasteland/ArmA3_Wasteland.Altis#283]
Issue: High winds affecting para dropping to the point that properly controlling decent (forward thrust into the wind) still results in player death.
Discussion: First of all, please allow me to “qualify” myself as a subject matter expert in military parachuting. I am a retired U.S. Army Infantry Airborne Ranger with many jumps under my belt and many operations performing the duties of DZ safety officer. For the sake of this audience, my assumption is that there are many with my qualifications but few that play Arma 3, even fewer who play Wasteland and fewer who play on A3Armory’s servers. I agree that this game can’t reproduce the realism of an actual para drop (especially with the “magic parachute” in the game). 
So let’s look at some of the reasons we use the parachute in A3Armory’s version of Wasteland (not all inclusive): 
1.	In conjunction with spawn beacons.
2.	A hasty exit from a building/cliff or a game bug in a building/cliff requiring you to use the magic parachute”.
3.	Ejecting from an aircraft (emergency or not.
4.	An airborne insertion in conjunction with a military operation (both combat and non-combat).
The wind issue can be very frustrating to the player who just died because they had to “roll the dice” on wind speeds. The reality is that a real world jumper would know the wind speeds and direction prior to doing it unless it was an emergency (eject or overcoming a game bug). Para dropping with the real world military is statistically about the safest task that one can do in the military. They take extraordinary measures to mitigate the risks of para dropping (this doesn’t account for death/injury by bullets). 
Coarse of actions (again, not all inclusive): 
1.	Include a wind speed/direction indicator in the game as an addon either displayed on screen or a purchased item in general store.
2.	Keep wind speed settings down to a realistic level for para dropping in the game.
Recommendation:
Because it wouldn’t add to the PBO file size, wouldn’t require any coding to be implemented in gameplay COA 2 is recommended.

**Comment by hobart666** [comment]
Have someone modify the dynamicweathereffects.sqf in the mission.

**Comment by AgentRev** [comment]
A3Wasteland wind is totally random, and varies between about 0 to 15 knots.

**Comment by hobart666** [comment]
But can be controlled.

// Wind vector strength never falls below this value. Must be greater or equal to 0 and less than or equal to _maximumWind.
// (Suggested value: 0);
_minimumWind = 0;

// Wind vector strength never exceeds this value. Must be greater or equal to 0 and greater than or equal to _minimumWind.
// (Suggested value: 8).
_maximumWind = 8;

**Comment by TastyDischarge** [comment]
Thank you very much! Your replies should be helpful with resolving this issue.
