### ISSUE TITLE
Starving to death too quickly if A3W_timeMultiplierDayset higher than 1

### ISSUE THREAD

**Issue by KingZogg** [A3Wasteland/ArmA3_Wasteland.Altis#285]
If you set the A3W_timeMultiplierDay multiplier to say 4 .. you will die of thirst really quickly.
It would be nice if the food and water variables were synced to match the time.
ie: if it's 4 then the decrease in food and water was reduced by 4 also.

**Comment by AgentRev** [comment]
That doesn't make any sense, food and water decrementation is not linked to the time of day, it is calculated in real time every second in a "while true sleep 1 then decrement" type loop.

**Comment by KingZogg** [comment]
Your right of course.... oops
