### ISSUE TITLE
A3W_vehicleThermals no longer used ?

### ISSUE THREAD

**Issue by KingZogg** [A3Wasteland/ArmA3_Wasteland.Altis#286]
I have set A3W_vehicleThermals to 1 but it does not seem to be used.
I can no longer see any A3W_vehicleThermals reference anywhere in the codebase.

**Comment by Classifed787** [comment]
server\functions\vehicleSetup.sqf
Open that up and scroll down to about line 24 and you should see it.

**Comment by AgentRev** [comment]
A3W_vehicleThermals never was a vanilla feature, it was a custom implementation by the TOP guys

**Comment by KingZogg** [comment]
Ahh.... ok thanks guys.
