### ISSUE TITLE
Building Material

### ISSUE THREAD

**Issue by Classified787** [A3Wasteland/ArmA3_Wasteland.Altis#287]
I am running V1.1 and have base building saving turned on and I have the building decay set to 14 days. It doesn't happen all the time or in a uniform way, but after a restart some of the base building material at just a couple players bases will disappear on new material that they just set in place and locked prior to the restart. I tested this last night at one of my players bases, and I watched him place 4 walls and lock them in place and after I restarted the server all 4 walls had disappeared. But he even stated that it did not happen all the time. I am using iniDB saving and my thought was that maybe he was locking items down between the server saving time. Just wanted to see if anybody else was having similar issue with this. Oh, and I just did a full server wipe about 1 week ago.

**Comment by LouDnl** [comment]
Having this issue sometimes too. Seems that when everything loads in for a brief time it's damagable.

**Comment by Classified787** [comment]
Not a problem  now.
