### ISSUE TITLE
Bugs with Marksman weapons/items and extDB2

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#294]
After pulling extDB2_beta branch, adding Marksman weapons and items, and upgrading extDB2 to v49, I found that Marksman weapons and items are not able to be saved correctly as well as all objects, and that vehicle store owners have moved slightly. But I can still buy vehicles. 
Here's the rpt log (partial, because the file is too big). 

http://pastebin.com/VaM33Ca3

Please note line 326 and 329.

**Comment by LouDnl** [comment]
Did you update your a3wasteland.ini?

**Comment by LouDnl** [comment]
Because they save without any problems with extDB2 on my server,

**Comment by AgentRev** [comment]
I don't know what is "boomerang_owner_type" but that's not vanilla and it's what's causing the error.

**Comment by LouDnl** [comment]
The Boomerang is an item Micovery created. Afaik it's not suited for extDB.
