### ISSUE TITLE
Bandwith issue

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#295]
I'm reporting this here because Dwarden is blaming A3Wasteland. Personally I think it has to be the game that's causing this but ok.

What happens is that starting 20+ players the bandwith usage goes insanly up and fps/cps drops. Then after a while  everything breaks down and bandwith and cps/fps drop all together.
More info here: http://forums.a3wasteland.com/index.php?topic=1395.0
And here: http://feedback.arma3.com/view.php?id=23593

**Comment by LouDnl** [comment]
http://dev.arma3.com/post/spotrep-00040 says 'Optimized: Network traffic'. Upward yeah..

**Comment by AgentRev** [comment]
It's either couple last game updates, or extDB2. Everything was working fine 3 months ago, it's now like many changes have been done since then lol...

**Comment by LouDnl** [comment]
Well theres someone on the forum claiming to have the same problem with a nearly vanilla Wasteland using extDB1.
I'm going to revert one server back to extDB1 today and I will try a new server with node.js. Just to be sure.

**Comment by LouDnl** [comment]
Got my main server running on extDB 1 now.
If this is not the problem I will set up a third node.js server as test.

**Comment by LouDnl** [comment]
Tested with extDB1 and this makes no difference. Gonna try and fill up a test server with iniDB tonight.

**Comment by Torndeco** [comment]
Personally you are wasting your time.

If there was an issue with extDB someone would have noticed months ago, like all those Altis Life RPG Servers.

Stop complicating things, like i said Dwarden just pointed out you are both using same extension.
He has done no debugging work on the issue, so he is wildly pointing out its the extension is grasping at straws.
They tweaked/improved Network bandwidth usage, so there is prob an issue with arma3 code that A3Wasteland has the bad luck of triggering it that is making it worse.

--------

If you really want to debug the issue + prove its not an extension or callExtension (makes no sense btw).

Keep it simply and just use Arma Profile Saving Scheme.
That way you can point a vanilla mission that is causing the issue in the bug tracker with no mods + no extensions.

**Comment by AgentRev** [comment]
I was pretty sure since the start that it's Bohemia's fault, I mean whenever A3W server owners report any kind of serious performance issue, Dwarden puts the blame on me and calls it a day.

**Comment by LouDnl** [comment]
Allright i've started a Vanilla mission on profile saving. Let's see if I can get it filled tonight :)

**Comment by LouDnl** [comment]
Well... Vanilla mission with profilenamespace saving hasn't shown any excess in bandwith usage yet. But then again haven't gotten the player count above 15.

**Comment by Torndeco** [comment]
[MGT]DB reporting the same issue with EpochMod with high player counts since the latest patch.
So its pretty safe to say issue is with Arma3

**Comment by LouDnl** [comment]
Not a problem with A3Wasteland imho. Continue here: http://feedback.arma3.com/view.php?id=23593

**Comment by LouDnl** [comment]
Just to add a note to this issue. I have been giving extensive logs to Bohemia from which they pinpointed several issues with the game. I hope they fix them soon :)

**Comment by LouDnl** [comment]
Update:

I'm feeding Dwarden extensive logs from my servers (very performance degrading).
Last updates from Dwarden:

He think it may have something to do with the built in vehicleamanager or even the headless client:
[code]what we actually were checking now was the AskForPilotLight it seems vehicles lights state were sent at rate 7000 / second to server
your problem on ongoing are updates to Vehicle (position, state) turret states etc
which is related to the simulation stuff (it seems all vehicles are re-enabled too often and then disabled and loop)[/code]


They are now testing internally with the Vanilla A3Wasteland.
[code]so we found some funky stuff like objects falling from 20km altitude on that mission
not sure yet if mission fault or else ... also the other stuff we fixed, well not correctly
so next week we will try dig into it more[/code]

**Comment by osuapoc** [comment]
The items falling from 20km (probably 10km-13km vertical) is probably something going on with the R3F system.  Instead of deleting/creating vehicles during load/unload, the R3F system just attaches them to the object [(random 3000), (random 3000), (10000 + random 3000)].  So if they somehow become detached, the would then plummet back to earth.
