### ISSUE TITLE
bug when joining ANY wasteland server

### ISSUE THREAD

**Issue by NonstopNonsense** [A3Wasteland/ArmA3_Wasteland.Altis#297]
when i join a wasteland server i cant select a team or squad. neither do i see any players in the lobby
when i join an end game server everthing works perfectly fine
i was playing wasteland yesterday without any problems and i havent changed anything since
i already tried restarting steam/my pc, verified my game chache and reinstalling the whole game

some screens of what i mean

selecting any random server with ppl on it
http://i.imgur.com/wAh4IdJ.jpg
when i join this server it looks like that
http://i.imgur.com/RDN1JIz.jpg
other servers like this endgame server works fine
http://i.imgur.com/LjN4MjP.jpg

and to make it even more confusing
some server seem to work (i tried like 100) but i didnt manage to figure out  if it has anything to do with the map, the version, the amount of players or the ping =/
but when i select a team bla bla and press ok to join the game it gets stuck at receiving data

thanks for any help

**Comment by LouDnl** [comment]
Could you try joining my servers let us know if you have the same problems?
http://www.gametracker.com/server_info/smeekes.mooo.com:2302/
http://www.gametracker.com/server_info/89.105.214.28:2322/

**Comment by NonstopNonsense** [comment]
the first one works. i can select a team and class and even play the game! :D 
the second one has the same problem. cant select a team or class =/

but i want to mention that i am trying to join a server that i was playing on the other day but now i cant anymore :,(

**Comment by LouDnl** [comment]
Can you post your client RPT log? Please make a pastebin of it or provide a download link.
Usually you can find this in C:\Users\USERNAME\Appdata\local\Arma3\

**Comment by NonstopNonsense** [comment]
;_;... wut?
instructions not clear enough =( pls explain what you want me to do like i am some kind of pleb. >-<
step by step nice and easy xD
i have alot of RPT in there and i have no clue what a pastebin is supposed to be D:
HALP

**Comment by LouDnl** [comment]
Get your latest RPT log file and upload it to www.wetransfer.com. Put the link here. Then we can look at your log file.

**Comment by NonstopNonsense** [comment]
http://workupload.com/file/dWJ3pnVn

your site was kinda strange so i just took another

**Comment by AgentRev** [comment]
lol anything but wetransfer, in fact please never give me anything from that site again

**Comment by LouDnl** [comment]
Always worked for me ;-)

**Comment by LouDnl** [comment]
Try starting the game without any mods, scripts or addons enabled. Then after this try joining a Wasteland server.
All i'm seeing is script errors in your log. These are either server faults or scripts you are loading yourself.

**Comment by NonstopNonsense** [comment]
the only mod i had enabled was epoch which i was playing since wasteland doesnt work=/
i also have battle royale but i wasnt enabled

so i disabled epoch and deleted battleroyale but still the same problem when i join

**Comment by Beefaloaf** [comment]
Since you're reaching out for help from this community and it's not a common issue, you probably shouldn't come in hot with addons and custom things running.

Give us the base vanilla setup so we can all view your scenario from the same perspective.
Could you re-post a vanilla .rpt?  No command lines right, just a straight launch?

Speaking of command lines, after posting a clean .rpt you could try running the game with a brand new profile folder...     stick these the following in the launch parameters of Arma and try, just remove them after you've tested:
```-name=Test -config=Test\server.cfg -cfg=Test\basic.cfg -profiles=Test```

Not trying to hijack the efforts of others here, it killed me when I saw "epoch mod" was running 2 days after the original request for help.

**Comment by NonstopNonsense** [comment]
http://workupload.com/file/httlAJEl

so i disabled all dlc and mods started amra up again and joined a wasteland server
i hope thats what you wanted me to do when you said "clean rpt"

**Comment by Beefaloaf** [comment]
Definitely better!  I'm not seeing where this log captures the start of the MP mission however...    specifically the line "Starting mission:".  This usually happen between lines 450-500 on a vanilla Arma3 install if you jump right into a server.

Here's my client .rpt as I join my server...     starting at about line 480.
```
15:06:01 EPE manager release (0|0|0)
15:06:01 EPE manager release (0|0|0)
15:06:01 EPE manager release (0|0|0)
15:06:01 EPE manager release (0|0|0)
15:06:01 Starting mission:
15:06:01  Mission file: NANA_A3Wasteland (__CUR_MP)
15:06:01  Mission world: Altis
15:06:01  Mission directory: mpmissions\__CUR_MP.Altis\
15:06:01 EPE manager release (0|0|0)
```

Your last .rpt seems to stop right about here at the EPE stuff.
This may be the wrong direction but, did you try the new profile folders? 

Perhaps LouDnl or Rev has more input on your log results.

**Comment by LouDnl** [comment]
Your RPT doesn't show anything peculiar but that it stops at the point that it does isn't good. 
Try removing the -mod= part from your startup line.

Otherwise delete arma 3 and reinstall.

**Comment by NonstopNonsense** [comment]
i did this   -name=Test -config=Test\server.cfg -cfg=Test\basic.cfg -profiles=Test but still the same problem
and i dont have a -mod= startup line and i already reinstalled it once=/

**Comment by LouDnl** [comment]
I suggest you deinstall arma, and the reinstall in another folder.

**Comment by NonstopNonsense** [comment]
i deleted arma and everything that was in my arma folder etc.
reinstalled it (again) still same problem=(

**Comment by osuapoc** [comment]
Did you also delete the ARMA data directory in your USER folder?

I've run into at least one other player that inexplicably had scripts that would not work for them for whatever reason, even after total reinstalls.

Another WAG would be to run a memtest and see if you're having some issue with your system memory.  Very long shot, but I've seen it cause weird bugs with other applications.

-----Original Message-----

**Comment by Beefaloaf** [comment]
Uninstalling everything should rule out if anything in the Arma folder was wonky.  The uninstall may not delete the other folders, where your settings and profiles are stored.  Check for these folders and delete them (no need to uninstall Arma again)

At this point, what do you have to lose?  :)
```
[username]\Documents\Arma 3
[username]\Documents\Arma 3 - Other Profiles
[username]\AppData\Local\Arma 3
[username]\AppData\Local\Arma 3 Launcher
```

**Comment by NonstopNonsense** [comment]
i did but it didnt help =(

**Comment by NonstopNonsense** [comment]
so nobody got any idea anymore?=(

**Comment by contactgus** [comment]
Post an RPT log for a successful connection and an unsuccessful one. In
fact, get at least two of each all from different servers and all with no
mods running
