### ISSUE TITLE
Saving DLC gear

### ISSUE THREAD

**Issue by nward** [A3Wasteland/ArmA3_Wasteland.Altis#300]
Hi guys,

I'm running a pretty vanilla A3Wasteland, and have imported the DLC commits.

I run ExtDB, on Linux.

I've noticed and other have commented, that DLC gear either isn't saved, or isn't restored - it doesn't survive a reconnect in any case.

I note that things seem to get saved to the DB OK, So it seems to be during the restore.

I haven't made any changes to my server to enabled the DLC or anything - is that required? I would have expected lots of things to fail if it were.. but I'm no expert!

**Comment by LouDnl** [comment]
Make sure you have ALL latest commits. I have no problems what so ever. So it must be on your end in the mission files.

**Comment by nward** [comment]
I have up to 217fa29, there doesn't seem to be anything since related to saving.

**Comment by LouDnl** [comment]
What items don't save?

**Comment by nward** [comment]
Marksmen DLC items.

I should note, I'm running Stratis, but of course the code is the same for this stuff.

My intention is to try and resolve this myself, I'm noting it here in case anyone has a similar issue, or if it's expected behaviour for the moment.

**Comment by LouDnl** [comment]
weapons? clothing? all of it?

**Comment by nward** [comment]
Yes, all Marksmen DLC items.

This includes the new ghillie suits, weapons, accessories.

**Comment by LouDnl** [comment]
Have you tried pulling the latest vanilla download of Github to see if it works then?
https://github.com/A3Wasteland/ArmA3_Wasteland.Stratis/archive/Development_Main.zip

**Comment by nward** [comment]
I have not, I have compared the Development_Main branch against my currently branch.

There are a handful of differences, where I have changed store prices, added my own map items/help text/etc., changed players' default headgear, and added clothes spawning in Vehicles.

There are no differences in any of the stuff that handles persistence.

It sounds like you didn't have to do anything to make the Marksmen DLC content work properly, and I appreciate that info, that gives me useful insight in to where I might look.

**Comment by LouDnl** [comment]
Well, at first I added the DLC myself. That worked fine. Then after Rev released his commits I used his. And it still works fine.

**Comment by nward** [comment]
Yep just like me. I reverted my DLC changes and applied the changes on Development_Main.

Worth noting the DLC content didn't work on either my own version, or on the "official" version. I had hoped that my version missed something, but that doesn't seem to be the case.

I will keep looking.

**Comment by AgentRev** [comment]
I haven't experienced this, but it is probably related to DLC restrictions enforced by the engine. It would have to be tested with the DLC disabled. It's certainly not caused by A3W, because the saving code treats all items equally, it doesn't check if it belongs to a DLC.

**Comment by nward** [comment]
Yeah, I figured this out finally last night when I had a bit of spare time. I'm running a couple of servers on the same machine so symlink stuff in to each server's dir, and had missed adding a symlink for marksmen - now I know how the DLC add ons work at least! I'll close this off, cheers.
