### ISSUE TITLE
1.44 update issues

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#304]
Just updated to 1.44 and seeing all kinds of issues with A3Wasteland. Gotta love BIS breaking things.

ANTI-HACK is picking up loads of:
2015/05/05, 17:14:40 "ANTI-HACK - Blocked remote execution: params=["bis_fnc_objectVar",false,false,false] args=[R Alpha 4-3:1 (Erisss) REMOTE]"
2015/05/05, 17:15:03 "ANTI-HACK - Blocked remote execution: params=["bis_fnc_objectVar",false,false,false] args=[R Bravo 1-2:1 (MavKev) REMOTE]"
2015/05/05, 17:15:43 "ANTI-HACK - Blocked remote execution: params=["bis_fnc_objectVar",false,false,false] args=[R Alpha 1-1:1 (Solaire of Astora) REMOTE]"
2015/05/05, 17:16:07 "ANTI-HACK - Blocked remote execution: params=["bis_fnc_objectVar",<NULL-object>,false,false] args=[<NULL-object>]"
2015/05/05, 17:16:10 "ANTI-HACK - Blocked remote execution: params=["bis_fnc_objectVar",false,false,false] args=[R Bravo 1-3:1 (Ade) REMOTE]"

And server/client is spamming:
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'BIS_fnc_preload_server' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'lowAdmins' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'highAdmins' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'serverOwners' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'bannedPlayerNames' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_startingMoney' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_showGunStoreStatus' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_gunStoreIntruderWarning' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_playerSaving' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_combatAbortDelay' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_unlimitedStamina' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_bleedingTime' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_teamPlayersMap' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_remoteBombStoreRadius' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_vehiclePurchaseCooldown' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_globalVoiceWarnTimer' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_globalVoiceMaxWarns' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_antiHackMinRecoil' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_spawnBeaconCooldown' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_spawnBeaconSpawnHeight' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_purchasedVehicleSaving' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_missionVehicleSaving' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_missionFarAiDrawLines' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmEnabled' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmMaxBalance' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmTransferFee' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmTransferAllTeams' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmEditorPlacedOnly' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmMapIcons' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_atmRemoveIfDisabled' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_uavControl' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_townSpawnCooldown' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_maxSpawnBeacons' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_savingMethod' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Write 'A3W_extDB_ServerID' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:03:41 Performance warning: SimpleSerialization::Read 'A3W_extDB_ServerID' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

and:
2015/05/05, 17:04:13 "WASTELAND SERVER - Started Main Mission Controller"
2015/05/05, 17:04:13 "WASTELAND SERVER - Main Mission waiting to run: mission_Convoy"
2015/05/05, 17:04:13 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 17:04:13 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

**Comment by AgentRev** [comment]
dafuq, goddamnit bis

> ask for optimizations for these types

the hell does that even mean

**Comment by LouDnl** [comment]
Gotta love em huh..
Those optimazations are just a load of crock. I think they just added another spam option to the RPT lol. What worries me more is the anti hack messages.

**Comment by AgentRev** [comment]
AH stuff shouldn't cause much problems, I'll look at it later

**Comment by LouDnl** [comment]
Allright, everything seems to work unless all the errors and messages.

**Comment by AgentRev** [comment]
You can try to add "BIS_fnc_objectVar" at https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/c3e9bebc25ff59a6957f92dec8b19aa67c9ded5f/server/antihack/filterExecAttempt.sqf#L54

**Comment by LouDnl** [comment]
What does it even do...

**Comment by LouDnl** [comment]
Hmm lol even BIS functions have problems:
2015/05/05, 20:04:45 Performance warning: SimpleSerialization::Read 'BIS_fnc_MP_packet' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
2015/05/05, 20:04:45 Performance warning: SimpleSerialization::Read 'BIS_fnc_MP_packet' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

**Comment by LouDnl** [comment]
Addid that function to the filterExecAttempt.sqf. Seems like its ok now :) Gonna push it to my live servers now.

**Comment by LouDnl** [comment]
Here's some more info from BI on the serialization stuff:
http://forums.bistudio.com/showthread.php?191516-Update-1-44-Getting-strange-errors-in-RPT!&p=2932399&viewfull=1#post2932399
https://community.bistudio.com/wiki/publicVariable
