### ISSUE TITLE
Tanks in Parking

### ISSUE THREAD

**Issue by Goldennugget197** [A3Wasteland/ArmA3_Wasteland.Altis#310]
I stored my tank in the parking garage form the outside expecting it to spawn back outside when i retrieve it. But as i went to go do so, i spawned inside the building and the doors where to small for me to fit it through. I thing it would be a good idea to have vehicles that are to big to spawn outside.
![2015-05-13_00002](https://cloud.githubusercontent.com/assets/12451822/7642931/ef3332f8-fa62-11e4-938f-7bba6a0d2f58.jpg)

**Comment by AgentRev** [comment]
> in the parking garage form the outside

You left it outside, or inside? Please clarify.

**Comment by Goldennugget197** [comment]
i left it outside. i went inside to the computer to store it. then the next day i retrieved it it spawned inside the garage.

**Comment by AgentRev** [comment]
What computer are you talking about exactly?

**Comment by Goldennugget197** [comment]
The Computer you use to select what vehicle you want to store or retrieve.

**Comment by AgentRev** [comment]
This is a custom addon made by someone else, which means it's not under responsibility of the A3W team. Check with your server owner.

**Comment by Goldennugget197** [comment]
Ok, thank you for your time.

**Comment by Gigatek1** [comment]
Post your report here. 
https://github.com/micovery/ArmA3_Wasteland.Altis

**Comment by AgentRev** [comment]
Afaik micovery has ceased development until further notice.
