### ISSUE TITLE
A3 Wasteland Installed - RPT Error Spam

### ISSUE THREAD

**Issue by GTXGAMING** [A3Wasteland/ArmA3_Wasteland.Altis#311]
GTXGaming are integrating your product into our services, please refer to the email we sent you.
Upon integrating I have found the following RPT errors when trying to figure out why extDB was not saving progress. We have to fully test each product before we can offer them to our client base.

Any help you can provide would be gratefully appreciated.

Kind Regards,

Karl Griffin
General Manager
GTXGaming.co.uk

13:57:04 "############################# A3Wasteland_v1.1b #############################"
13:57:04 "WASTELAND SERVER - Initializing Server"
13:57:04 "Applying U_IG_Guerilla1_1 as uniform for GunStore4"
13:57:04 Performance warning: SimpleSerialization::Write 'A3W_network_compileFuncs' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:04 "ANTI-HACK: Started."
13:57:04 Performance warning: SimpleSerialization::Read 'A3W_network_compileFuncs' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:04 "Applying U_I_CombatUniform_tshirt as uniform for GunStore3"
13:57:04 "Applying U_IG_Guerilla2_2 as uniform for GenStore1"
13:57:04 "Applying U_O_SpecopsUniform_blk as uniform for GunStore2"
13:57:04 "Applying U_B_SpecopsUniform_sgg as uniform for GunStore1"
13:57:04 Performance warning: SimpleSerialization::Write 'BIS_fnc_preload_server' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:04 "Applying U_IG_Guerilla2_3 as uniform for GenStore2"
13:57:05 Performance warning: SimpleSerialization::Read 'BIS_fnc_preload_server' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 "Applying U_IG_Guerilla3_1 as uniform for GenStore3"
13:57:05 "Applying U_Competitor as uniform for VehStore3"
13:57:05 "Applying U_Competitor as uniform for VehStore2"
13:57:05 "Applying U_Competitor as uniform for VehStore1"
13:57:05 "WASTELAND SERVER - Initializing Server Relations"
13:57:05 "WASTELAND SERVER - Initializing Server Vars"
13:57:05 "WASTELAND SERVER - Initializing Server Compile"
13:57:05 Performance warning: SimpleSerialization::Write 'lowAdmins' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'highAdmins' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'serverOwners' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'lowAdmins' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'highAdmins' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'serverOwners' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'bannedPlayerNames' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'bannedPlayerNames' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 "WASTELAND SERVER - Server Compile Finished"
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_startingMoney' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_showGunStoreStatus' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_gunStoreIntruderWarning' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_playerSaving' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_combatAbortDelay' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_unlimitedStamina' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_bleedingTime' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_teamPlayersMap' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_remoteBombStoreRadius' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_vehiclePurchaseCooldown' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_globalVoiceWarnTimer' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_globalVoiceMaxWarns' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_antiHackMinRecoil' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_spawnBeaconCooldown' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_spawnBeaconSpawnHeight' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_purchasedVehicleSaving' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_missionVehicleSaving' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_missionFarAiDrawLines' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmEnabled' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmMaxBalance' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmTransferFee' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmTransferAllTeams' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmEditorPlacedOnly' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmMapIcons' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_atmRemoveIfDisabled' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_uavControl' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_startingMoney' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_showGunStoreStatus' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_gunStoreIntruderWarning' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_playerSaving' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_combatAbortDelay' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_unlimitedStamina' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_bleedingTime' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_teamPlayersMap' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_remoteBombStoreRadius' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_vehiclePurchaseCooldown' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_globalVoiceWarnTimer' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_globalVoiceMaxWarns' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_antiHackMinRecoil' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_spawnBeaconCooldown' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_spawnBeaconSpawnHeight' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_purchasedVehicleSaving' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_missionVehicleSaving' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_missionFarAiDrawLines' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmEnabled' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmMaxBalance' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmTransferFee' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmTransferAllTeams' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmEditorPlacedOnly' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmMapIcons' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_atmRemoveIfDisabled' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_uavControl' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Unable to get file version size: .\extDB.dll
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_savingMethod' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 "[extDB] Startup..."
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_savingMethod' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 "[extDB] Connected to database"
13:57:05 "[extDB] Initialized DB_CUSTOM_V3 protocol"
13:57:05 "[extDB] Initialized MISC protocol"
13:57:05 "[extDB] Environment setup..."
13:57:05 "[extDB] Locked"
13:57:05 Performance warning: SimpleSerialization::Write 'A3W_extDB_ServerID' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 Performance warning: SimpleSerialization::Read 'A3W_extDB_ServerID' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:05 "[extDB] Startup complete!"

13:57:08 Performance warning: SimpleSerialization::Write 'A3W_serverSetupComplete' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:08 Performance warning: SimpleSerialization::Read 'A3W_serverSetupComplete' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

13:57:40 Performance warning: SimpleSerialization::Write 'A3W_serverSpawningComplete' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:40 "[INFO] A3W territory capturing is ENABLED"
13:57:40 "WASTELAND SERVER - Initializing Missions"
13:57:40 Performance warning: SimpleSerialization::Read 'A3W_serverSpawningComplete' is using type of ,'CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:40 "WASTELAND SERVER - Started Main Mission Controller"
13:57:40 "WASTELAND SERVER - Main Mission waiting to run: mission_Coastal_Convoy"
13:57:40 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:40 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:41 "A3W - 0 baseparts and objects have been saved with extDB"
13:57:45 "WASTELAND SERVER - Started Money Mission Controller"
13:57:45 "WASTELAND SERVER - Money Mission waiting to run: mission_SunkenTreasure"
13:57:45 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:45 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:50 "TERRITORY SYSTEM: _realLoopTime was 10.001"
13:57:50 "WASTELAND SERVER - Started Side Mission Controller"
13:57:50 "WASTELAND SERVER - Side Mission waiting to run: mission_TownInvasion"
13:57:50 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:50 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:55 "WASTELAND SERVER - Started Main Mission 2 Controller"
13:57:55 "WASTELAND SERVER - Main Mission 2 waiting to run: mission_HostileHeliFormation"
13:57:55 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:57:55 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:58:00 "TERRITORY SYSTEM: _realLoopTime was 10.005"
13:58:00 "WASTELAND SERVER - Started Money Mission 2 Controller"
13:58:00 "WASTELAND SERVER - Money Mission 2 waiting to run: mission_MoneyShipment"
13:58:00 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:58:00 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:58:05 "WASTELAND SERVER - Started Side Mission 2 Controller"
13:58:05 "WASTELAND SERVER - Side Mission 2 waiting to run: mission_Outpost"
13:58:05 Performance warning: SimpleSerialization::Write 'messageSystem' is using type of ',TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types
13:58:05 Performance warning: SimpleSerialization::Read 'messageSystem' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

**Comment by GTXGAMING** [comment]
I also forgot to mention.

I used the Release_Files and then extracted the extDB pack. Please let me know if you require further information, I am here 12 - 16 hours every day, always working.

**Comment by LouDnl** [comment]
Please post your extDB log. Located in /extDB/logs

**Comment by LouDnl** [comment]
And please use https://gist.github.com/

**Comment by GTXGAMING** [comment]
I have done this for you sir:
https://gist.github.com/GTXGAMING/96403ccb2c0566f691ab#file-extdb-logs-2015-5-21

**Comment by LouDnl** [comment]
Everything seems in order. Can you post the full server RPT log of a server that has run about 30 minutes ~ 1 hour please?

**Comment by GTXGAMING** [comment]
Sorry for the delay sir, this is an RPT from the dev server running 6 hours.
https://gist.github.com/GTXGAMING/8ad02abf7e4fa3b38fbc#file-gistfile1-txt

**Comment by LouDnl** [comment]
Everything looks fine. You even have a saved vehicle in your database.

Have you tried buying vehicles and buying objects and locking them?

There are no errors in your RPT stating that extDB isnt working. Nor are they in your extDB log.

13:57:05 "A3Wasteland - world persistence loaded 0 objects from extDB"
13:57:06 "A3Wasteland - world persistence loaded 1 vehicles from extDB"

14:00:43 "A3W - 0 baseparts and objects have been saved with extDB"
14:01:13 "A3W - 1 vehicles have been saved with extDB"

**Comment by AgentRev** [comment]
If you are referring to the SimpleSerialization stuff, it's Bohemia's fault, they added that useless junk in the last update.

**Comment by GTXGAMING** [comment]
Ah okay yes that was all I was referring to.
Thank you both for verifying this for me.

Can you also tell me other than Altis / Stratis, I have seen other people host other maps for A3W. Do you know were I can get a hold of the files please?

**Comment by defused** [comment]
(sorry to interrupt)

Hi Karl Griffin, glad to see you are adding Wasteland to your products role.

Im a client of your A3 vannila edition and i should advise you that if are planning to add A3Wasteland to your products you should be aware that since 1.42 update Wasteland servers are randomly crashing and you will probably have problems with your clients like im having with my server hosted on your machines.

The problem is addressed here and i advise you to wait for the next update or update the binary to last perf 

http://feedback.arma3.com/view.php?id=23986

Sorry to interrupt you guys

**Comment by GTXGAMING** [comment]
@defused Thank you very much for taking the time to reply here, I don't know about @AgentRev but I am very much aware of the issues surrounding the random crashing that is occurring on "Some" A3Wasteland servers. I do plan to use Dwarden's pre-released 1.44 PROF/PERF v2 CHIMERA build with our distribution as I am sure an official release via steam would take between 1 - 4 additional weeks from now.

@AgentRev not sure if you read my last but here it is:

"I have seen other people host other maps for A3W. Do you know were I can get a hold of the files please?"

**Comment by AgentRev** [comment]
The other maps are non-official ports maintained by third parties, and as such they all have a varying number of addons incorporated into them. You can check @TOPARMA's repositories, they maintain ports for Chernarus and Taviana, but they are heavily modified and make extensive use of the RHS mod, so they're not for everyone. They also have a Bornholm port, but I think they abandoned it.

**Comment by JoSchaap** [comment]
@Gtxgaming you should really check out our forums at a3wasteland.com

which maps would you be interested in? 


Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: GTXGAMING <notifications@github.com> 
Datum:22-05-2015  14:25  (GMT+01:00) 
Aan: "A3Wasteland/ArmA3_Wasteland.Altis" <ArmA3_Wasteland.Altis@noreply.github.com> 
Onderwerp: Re: [ArmA3_Wasteland.Altis] A3 Wasteland Installed - RPT Error Spam
  (#311) 

@defused Thank you very much for taking the time to reply here, I don't know about @AgentRev but I am very much aware of the issues surrounding the random crashing that is occurring on "Some" A3Wasteland servers. I do plan to use Dwarden's pre-released 1.44 PROF/PERF v2 CHIMERA build with our distribution as I am sure an official release via steam would take between 1 - 4 additional weeks from now.

@AgentRev not sure if you read my last but here it is:

"I have seen other people host other maps for A3W. Do you know were I can get a hold of the files please?"

**Comment by nerdalertdk** [comment]
Its relatede to sending structured text

> Just to close the loop. These messages were useful as it highlighted an issue with a global variable I had. The variable was an array of two values, the one was string and the other was structured text. The structured text value was causing performance issue because it couldn't be serialized properly. Changing to string sorted it out.

Source: http://epochmod.com/forum/topic/35045-arma-3-144-performance-warning/

i will make a pull if my fix works
