### ISSUE TITLE
Random ban. 

### ISSUE THREAD

**Issue by Reaper2** [A3Wasteland/ArmA3_Wasteland.Altis#312]
I just got randomly banned from the server for a certain time. My game name is Reaper which theres maybe 2 or 3 more reapers so idk if maybe one of them did something but i was just minding my own business when it told me i got banned.

**Comment by AgentRev** [comment]
We don't handle server bans here, we're just developers. Reach your server owner.

**Comment by Reaper2** [comment]
This is bullshit is this you guys banning the wrong guy or is it a connection issue on my end? My daughter flipped the switch to our router i reconnect and two minutes later im randomly banned.

**Comment by Reaper2** [comment]
Ok thanks

**Comment by AgentRev** [comment]
A3Wasteland does not own any official server, people just take the mission and host it on their server, as such we have no authority over bans.
