### ISSUE TITLE
1 miljon dissapeared from my bank

### ISSUE THREAD

**Issue by mesejas** [A3Wasteland/ArmA3_Wasteland.Altis#313]
When i logged in my bank 1 miljon was gone and also my weapon the lynx was gone and my back pack was gone and also i had another vest on im really pissed off atm

**Comment by AgentRev** [comment]
We are aware of the problem that causes this to happen, but we haven't found a way to fix it yet (#244). Please note that the A3Wasteland team does not own servers, you should check with your server's admin if you can get a compensation.
