### ISSUE TITLE
Trying to join "EpiX Wasteland" for stratis

### ISSUE THREAD

**Issue by Tylerdabro** [A3Wasteland/ArmA3_Wasteland.Altis#314]
After one night of playing a hacker came on who then killed everyone then kicked everyone, which gave me an error message. Now, the next day trying to join the same server, right when it puts me in, Arma crashes and then gives me errors again. Any ideas?

**Comment by Cael817** [comment]
Hi, is it something like "ForceQuit.sqf" not found? In that case you have probably been flagged as a "hacker" (which really are just cheaters an script kiddies) on that particular server. In that case you need to contact the server owner/admin to get it fixed. If you have trouble finding out who owns the server some of the admins list their servers at the A3W forums http://a3wasteland.com/
