### ISSUE TITLE
Scripts 

### ISSUE THREAD

**Issue by silenthitter** [A3Wasteland/ArmA3_Wasteland.Altis#315]
I was wondering where I can find the ingame revive script and magic parachute script, because I would like to change criteria on the scripts. And was wondering if there is a vanilla versions of them on armaholic.

**Comment by AgentRev** [comment]
Our revive system is based on <a href="/farooqaaa/far_revive">Farooq's Revive</a>, but it is heavily modified beyond its original form, in such a way that it has become intermingled with the A3W mission beyond possibility of having it standalone without major alterations.

I made the magic parachute script specifically for A3W as well, so there is no standalone version.
