### ISSUE TITLE
Curious about long standing bug with no support

### ISSUE THREAD

**Issue by ReaperDG** [A3Wasteland/ArmA3_Wasteland.Altis#317]
I posted a well documented "Issue" 28 days ago and had the specific servers Admin post his attempted fixes for the bug. It was posted so the developers of A3Wasteland can get visibility and start the process of fixing this bug. I used the right channels to inform you of this bug but have no heard form anyone. As if no one cares or no one is active on this Github. Which is weird because it was made for this specific reason. If you aren't going to do anything about fixing this bug then just say so, don't leave it in the queue to rot. I'm one of the admins on the server and I'm tired of hearing about the bug. I will refer to my OP. Thanks

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/305

**Comment by AgentRev** [comment]
Look man, A3W is a hobby and is offered free of charge, don't come complaining if some bugs aren't fixed outright. I was busy with college finals up until a couple days ago, so obviously I did not have any time to work on anything since. Acting entitled will not get you anywhere with me.
