### ISSUE TITLE
Group Management Bug 

### ISSUE THREAD

**Issue by Kallamigkungen** [A3Wasteland/ArmA3_Wasteland.Altis#318]
Hi, me and my friend have problem with the group management.
I will let the Picture speak for itself!  Anyone know any fix for it ? 

Cheers

![problems](https://cloud.githubusercontent.com/assets/12799013/8037253/00e267aa-0dfd-11e5-89ab-dd641ae007fb.jpg)

Ps. my other friend can see people normaly.

**Comment by AgentRev** [comment]
![Stream-Friendly](http://thezombieinfection.com/wiki/images/thumb/9/95/StreamUI2.png/600px-StreamUI2.png)

**Comment by Kallamigkungen** [comment]
Thx !
