### ISSUE TITLE
Possible double deathcount

### ISSUE THREAD

**Issue by Cael817** [A3Wasteland/ArmA3_Wasteland.Altis#321]
I have a hard time to test this at the time but it seems that if you get incapacitated it counts one towards your deaths, and then if someone "finishes you off" before you press respawn you get one more death.
Not really an issue, more of an inconvenience

**Comment by AgentRev** [comment]
Bug resurfaced while I was testing revive stuff, the "Killed" event handler is called twice.

**Comment by AgentRev** [comment]
Fixed https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/61494fe22c09be1fdb71d24f4887281fff389cbe
