### ISSUE TITLE
A3W_extDB_Lock Option

### ISSUE THREAD

**Issue by Torndeco** [A3Wasteland/ArmA3_Wasteland.Altis#322]
This is a bad option to allow people to disable

1)
If you don't lock extDB2, a hacker that manages to remote execute some code on server.
They will be able to enable SQL_RAW and just wipe a servers database, or update all players bank money to zero etc
By either reading the A3W_extDB_databaseID variable or the async function itself, all they need is the random Database ID.

2)
The setup stage for extDB2 is not thread safe (its done by design for performance reasons).
If someone adds a Protocol && if it causes a rehash on a std::unordered_map container.
extDB2 will crash if there is any background threads queued up or working at the same time.

**Comment by AgentRev** [comment]
Well I guess I could remove it from the config SQFs, I added it so I can reload the a3wasteland.ini on the fly without restarting the game when I make edits to it, my main testbed is in-game LAN hosting, not arma3server.exe

**Comment by AgentRev** [comment]
I guess you haven't noticed, but the "A3W_extDB_Debug" option for extDB1 also skips the lock, and it's been like that since its initial implementation:

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/b45ef08d4bdc17fc2ca031b88a1670d5e26fc833/persistence/server/setup/extDB/init.sqf#L64
