### ISSUE TITLE
I was banned for no reason!

### ISSUE THREAD

**Issue by foxheadalpha** [A3Wasteland/ArmA3_Wasteland.Altis#323]
I was playing on, A3Armory.com | A3Wasteland Altis #1 | Full Save | $1500 Start, and got glitched into someones group. So i teleported on their beacon, and then landed. I got kicked for to high of ping, and then when i got back on seconds later I get kicked. I tried to get back on and It says "You were Banned"! I don't know why i was banned but I really wan't to be unbanned, Admin please help.

**Comment by AgentRev** [comment]
If you were banned from an A3Armory.com server, then obviously you need to go on on www.a3armory.com for help

**Comment by foxheadalpha** [comment]
Okay thanks, I am new to this stuff I still am understanding it.
