### ISSUE TITLE
Wasteland Mod not working after Arma 3 update

### ISSUE THREAD

**Issue by JA3S** [A3Wasteland/ArmA3_Wasteland.Altis#330]
It seems like since the Arma 3 update to 1.48 the ini file is not being read none of the functions for your Wasteland mod are working. Has anyone one else have seen this problem?

Best Regards
Jaeger

**Comment by AgentRev** [comment]
v1.1b and below are no longer working due to changes made to the game, please update to v1.2

**Comment by LouDnl** [comment]
What ini file? Do you mean main_config.sqf?

**Comment by JA3S** [comment]
Sorry forgot the "t" (init.sqf). Thank you for answering my question AgentRev.

**Comment by hobart666** [comment]
Rev I thought the fn_allPlayers took care of everything.  Or was there more
dysfunction?

**Comment by AgentRev** [comment]
No there shouldn't be, I just gave the easiest solution that didn't require editing. You should still update to v1.2 for the added stuff thought.

**Comment by hobart666** [comment]
Ok thank you.
