### ISSUE TITLE
Objects don't get deleted from database

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#332]
We use the implementation where the headlessclient saves objects. We use 1 headlessclient for both caching objects and saving objects.
We can see in our database that all objects that are saved get their creation date and last interaction date reset about 4-6 minutes after each restart to that exact time. This is around the time the headless client makes it's first save run.
Due to this objects are rising ingame and FPS are ofcourse dropping.
I have disabled HC saving for after our next restart. I will report back with the findings.

**Comment by ancientevil** [comment]
Sounds good!
Please let me know your findings! Cheers /ancient

**Comment by ancientevil** [comment]
We are trying this to right now

**Comment by LouDnl** [comment]
You can check in your database what the creation and last interaction dates are.

**Comment by ancientevil** [comment]
![serverload](https://cloud.githubusercontent.com/assets/10650117/8765737/0ae97f38-2e1c-11e5-978e-b57147b0228f.jpg)
Database show interaction on every item on exakt same intervals yes

**Comment by Jermin** [comment]
I'm not using HC at all yet I'm still getting client FPS drop.

**Comment by LouDnl** [comment]
I ruled out the headlessclient saving. It happens when the server is handling the saving too.

**Comment by LouDnl** [comment]
Also I've noticed that the reset of last interaction and creation time/date doesn't apply to objects that are saved because of A3W_extDB_SaveUnlockedObjects is set to 1.

**Comment by ancientevil** [comment]
SOme of our players complaining about the textures making clientFPS drops. Textures on hospital kavala :/

**Comment by LouDnl** [comment]
Happens on our servers too

**Comment by AgentRev** [comment]
LouD, you made me spend an hour trying to trace down a bug, when the problem actually is that you have not merged correctly:

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/master/persistence/server/world/oLoad.sqf#L79-L84
https://github.com/LouDnl/ArmA3_Wasteland.Altis/blob/NL-United/persistence/server/world/oLoad.sqf#L81-L85

Please start using git merge immediately, I will not help you anymore if you keep pushing commits like `LouDnl authored X ago - AgentRev: <commit message>`

If you were using git merge, it should be saying `AgentRev authored X ago - <commit message>` along with some `Merge remote-tracking branch 'remotes/A3W/master' into NL-United`

**Comment by LouDnl** [comment]
Thank you for looking Rev. This is what I used to do untill i kept getting merge errors which I was unable to solve. The only way was for me to add the commits by hand. That's when I started the way I do it now. I have no idea how to work around merge errors with GitHub for Windows.

**Comment by AgentRev** [comment]
The answer is simple: do NOT use GitHub for Windows, it's the worst piece of crap you can possibly use for such a task.

**Comment by LouDnl** [comment]
Then what is an easy to learn program to use for this?

**Comment by ancientevil** [comment]
sourcetree i´m using.. :)

**Comment by osuapoc** [comment]
Source tree is what I use.

-----Original Message-----

**Comment by AgentRev** [comment]
I use TortoiseGit because of the shell integration. All your files in a repository are marked with small icons to indicate their status, like committed, added, modified, conflicted, deleted. There is no staging, if you want to commit you simply check the files your want to commit from a list and it's done.

When you want to merge, all you gotta do is fetch the vanilla remote, then open Merge and select the vanilla branch you want, if there are no conflicts all is good and you can push.

If there are conflicts, it will suspend the merge process and allow you to fix the conflicts one by one until none remains, after which you can commit and push.

**Comment by LouDnl** [comment]
So how would I pull over all my commits without the AgentRev: part to the master branch? Can you select which commits you want with either TortoiseGit or Sourcetree?

**Comment by ancientevil** [comment]
just fetch and then cherrypick in sourcetree or merge everything. Like I did from yours hehe..

Are there more conflicts btw?

**Comment by AgentRev** [comment]
Merging bring in everything in sync, there is no commit selection. First you merge, and if you wish to remove something then just undo the changes from commits you don't want and commit that on top of it. Or you can also manually remove the changes from any file if you are in conflict resolve mode, which will be committed as part of the merge.

**Comment by LouDnl** [comment]
I've overlooked all commits from the past month and the only line I missed was this exact line in oload.sqf. I've installed SourceTree and will pull in all new commits using this. After I get used to it that is.

**Comment by AgentRev** [comment]
If you cherrypick the commits, it will break history and may cause you to do more work than if you merge. WIth cherrypicking, each commit is applied individually, and you gotta fix the conflicts as it progresses. With merging, there is only one conflict resolving step.

**Comment by LouDnl** [comment]
Thanks for getting my main Altis repo back in sync with Vanilla Wasteland Rev. Kisses :+1:

**Comment by ancientevil** [comment]
Shall i sync with main agentrevs or with Louds repo now after he is in sync?

Little confused sometimes with github but still learning.
