### ISSUE TITLE
Respawn teleport bug

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#334]
At the respawn UI, clicking on the random button and then immediately clicking on the group management button, one can change the spawn town to another random city.

**Comment by LouDnl** [comment]
Can conform this.
Make sure you have preload spawn checked. Then click the random button and quickly press the groupmanagement button and keep the screen open. Wait for yourself to spawn and the respawn dialog appears again. You can do this over and over and over.
Only works for me if the preload spawn button is checked. This makes the spawn loading longer. If uncheck your have to be really really quick.

**Comment by AgentRev** [comment]
d5cb2491c8abdac1eb3b5402dd8cf3170e1037b1

**Comment by mastervova** [comment]
please write where the remove night  vision with UAVs "AR-2 darter"
