### ISSUE TITLE
Inivisble spawn beacons

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#336]
Spawn beacons (and it seems warchests) go invisible after a server restart.

http://forums.a3wasteland.com/index.php?topic=1823.0

**Comment by AgentRev** [comment]
Oh, I know the problem. I added an hideObjectGlobal while the object is being set up. Except, I forgot that I also put an exitWith clause for deployed objects before the object is unhidden.

**Comment by gtoddc** [comment]
is this it?

	_allowed = switch (true) do
		{
			case (call _isWarchestEntry):       { _warchestSavingOn };
			case (call _isBeaconEntry):         { _beaconSavingOn };
			case (_class call _isBox):          { _boxSavingOn };
			case (_class call _isStaticWeapon): { _staticWeaponSavingOn };
			default                             { _baseSavingOn };
		};

		if (!_allowed) exitWith {};

		_objCount = _objCount + 1;
		_valid = true;

		{ if (typeName _x == "STRING") then { _pos set [_forEachIndex, parseNumber _x] } } forEach _pos;

		_obj = createVehicle [_class, _pos, [], 0, "None"];
		_obj allowDamage false;
		_obj hideObjectGlobal true;
		_obj setPosWorld ATLtoASL _pos;

**Comment by LouDnl** [comment]
My guess is you add it here like I did. Will this work like it should Rev?

		if (_unlock) exitWith
		{
			_obj setVariable ["objectLocked", false, true];
			_obj hideObjectGlobal false; // Temporary fix for invisible spawn beacons and warchests
		};

**Comment by AgentRev** [comment]
Yes that's the easiest way, but the fix I will actually do is use an "if then else" instead of " if exitWith"

**Comment by LouDnl** [comment]
Ok thanks Rev. I'll add this untill you create the real fix.

**Comment by LouDnl** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/fb2dcae909537050e6ab7af4eaed51a349f26e61
