### ISSUE TITLE
How i can setup an A3Wasteland Server with MySql...

### ISSUE THREAD

**Issue by niconowy** [A3Wasteland/ArmA3_Wasteland.Altis#337]
Hello guys,

have somebody a guide how i can setup an A3Wasteland Server with MySql and the other things.
Sorry for bad english im german :)

**Comment by AgentRev** [comment]
Now, do you have working Arma server? or you haven't figured that part yet?

**Comment by niconowy** [comment]
Thanks!. I have already a Wasteland Server this here can be closed

**Comment by LouDnl** [comment]
You can close it yourself.
