### ISSUE TITLE
Headlessclient showing in scoreboard

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#338]
He aint never killed nobody ;-)
http://i.imgur.com/B2iMlZs.jpg

This is just after a restart only btw.

**Comment by AgentRev** [comment]
lelwat

**Comment by AgentRev** [comment]
Oh, it only shows if you're logged in as the main admin... still weird.

**Comment by AgentRev** [comment]
The new `allPlayers` command includes headless when logged in as admin... My previous implementation pulled data from `allUnits` and `allDeadMen`, which doesn't contain the headless regardless.

**Comment by hobart666** [comment]
Mine does this occasionally after a restart as well, shows up on blufor a kick and he reconnects back to his place... noticed this months ago.

**Comment by AgentRev** [comment]
Well, does everyone see him or just the admin?

**Comment by hobart666** [comment]
Me? Everyone.

**Comment by hobart666** [comment]
Sometimes they even have found him on the map.

**Comment by AgentRev** [comment]
Yeah, that's most likely an Arma bug then.

**Comment by hobart666** [comment]
Yea man, it's not intolerable. I do have some regs complaining about some vehicles disappearing after some restarts and when I was running two HC's we had vehicles that were either detroyed & salvaged or sold actually return on restart, that has seemed to subside since I'm only running one.

**Comment by AgentRev** [comment]
That's exactly the kind of things you need to report to me. Nobody ever reported problems with HC saving, which for me, means all is well and good...

**Comment by LouDnl** [comment]
No problems here with HC saving.

OT: And I wasn't logged in as admin :-) and our HC never logs in as Blufor.

**Comment by hobart666** [comment]
Well then I guess the detail I have is it was only affecting me while running two. Both HC directories mirror the A3master directory.
Settings I was using at the time:
// Headless client settings
A3W_hcPrefix = "A3W_HC";           // Prefix of the headless client unit names in mission.sqm
A3W_hcObjCaching = 1;              // Enable headless client object caching (0 = no, 1 = yes)
A3W_hcObjCachingID = 1;            // ID of the headless client in charge of object caching (1 or 2)
A3W_hcObjSaving = 1;               // Enable headless client vehicle & object saving (0 = no, 1 = yes)
A3W_hcObjSavingID = 2;           // ID of the headless client in charge of object saving (1 or 2)

**Comment by AgentRev** [comment]
http://feedback.arma3.com/view.php?id=25497

**Comment by AgentRev** [comment]
217903ba44c4e0d7a885ed2d5bfa298e757a3589
