### ISSUE TITLE
Ghosting timer

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#345]
I have A3W_extDB_GhostingTimer = 5*60; on my two servers running Altis. Both have the same environment name. But for some reason players can move from one server to the other without a ghosting timer kick? Am I doing something wrong?

**Comment by AgentRev** [comment]
The ghosting timer doesn't kick, it shows a timer saying how long until your player will start loading.

**Comment by LouDnl** [comment]
Ok will have to try that then

Verstuurd vanaf mijn iPhone

Op 17 aug. 2015 om 12:58 heeft Agent Revolution <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


The ghosting timer doesn't kick, it shows a timer saying how long until your player will start loading.

-

**Comment by LouDnl** [comment]
Works as intended.
