### ISSUE TITLE
Wasteland settings broken after Arma 3 Patch

### ISSUE THREAD

**Issue by HARDCOREMANN** [A3Wasteland/ArmA3_Wasteland.Altis#351]
It looks as if all settings read from another source admin menu and all settings will not be accepted, for example,
Money at the start is 100 000. But there we started with 100, and so on

**Comment by AgentRev** [comment]
You need to add `-filePatching` to the arma3server command line

**Comment by HARDCOREMANN** [comment]
im a noob im sorry how i can do this ?

**Comment by AgentRev** [comment]
Well how is your server setup?

**Comment by HARDCOREMANN** [comment]
Windows-Server couse im a noob xD i download arma3 server over steam and add wastelandfiles wasteland run over mysql was allrigt before patch comes out
i overwritten old files whit new on i get only problems by last 2 patches before i never get any problems 

ty for your help and im sorry for my bad english

**Comment by HARDCOREMANN** [comment]
btw after patch all stuff on your server works ?

**Comment by AgentRev** [comment]
Okay, how do you start the server? Via Steam, TADST, or a shortcut?

**Comment by HARDCOREMANN** [comment]
is start over TADST

**Comment by AgentRev** [comment]
Find the "Parameters" textbox in the "Details" tab, and add `-filePatching` at the end

**Comment by HARDCOREMANN** [comment]
YOU ARE A HERO ITS WORKS TY!!! 

Maybe you can explain me what it change now ? must i dot this now on every serverstart or only after new patch comes out ?

**Comment by osuapoc** [comment]
https://community.bistudio.com/wiki/Arma_3_Startup_Parameters

-----Original Message-----

**Comment by HARDCOREMANN** [comment]
TY for your link but there is no parameter -filePatching or how it can explain it me ?

**Comment by AgentRev** [comment]
You only needed to do it once, keep it there from now on.

**Comment by HARDCOREMANN** [comment]
OK thanks for your help and time :)
