### ISSUE TITLE
Scroll wheel enemy spot

### ISSUE THREAD

**Issue by CommandoUKSF** [A3Wasteland/ArmA3_Wasteland.Altis#355]
Would it be possible please to remove or inhibit the 'scroll wheel' enemy spot capability from ARMA 3 Wasteland please?

This 'cheat' is being used increasingly and spoils what is otherwise a truly superb game mode. People simply scroll wheel in all directions and then have X-ray vision to spot you in game

Many thanks for all your hard work with Wasteland, it is appreciated by the community and us users

Thanks

**Comment by AgentRev** [comment]
This is actually a server difficulty setting, it has nothing to do with Wasteland itself.

**Comment by AgentRev** [comment]
If you know the server owner, ask him to put the following in the "Server.Arma3Profile" file:

	class Difficulties
	{
		class Regular
		{
			class Flags
			{
				EnemyTag=0; // disable scrollwheel enemy info
				AutoSpot=0; // disable autospotting
				Map=0; // disable spotted enemy icons on map
			};
		}
	};

**Comment by CommandoUKSF** [comment]
Thanks very much, I will let the TOP EAST/WEST guys know now

**Comment by AgentRev** [comment]
Yo @l0dac, can you compare your difficulty settings with the above?

**Comment by l0dac** [comment]
Our Arma3Profile is as follows:

class regular
	{
		class Flags
		{
			AutoSpot=0;
			Map=0;
			AutoGuideAT=0;
			enemyTag=0;
			friendlyTag=0;
			CameraShake=0;
		};
	};

**Comment by AgentRev** [comment]
Well, great... After some testing, it appears the scrollwheel enemy info is somehow always on in Regular difficulty, unless you disable the weapon crosshair entirely with `WeaponCursor=0;`. However, scrollwheel text doesn't show up at all in Veteran, regardless of difficulty settings, even with crosshair enabled. Good job BIS, as usual...
