### ISSUE TITLE
Suggestion: Donor/Subscriber spawn menu (Monetization)

### ISSUE THREAD

**Issue by Zer01BR** [A3Wasteland/ArmA3_Wasteland.Altis#359]
I've been trying to come up with something to give at least some advantage to our server subscribers and maybe I found something.

BIS rules for server monetization require that donor perks don't provide gameplay advantages, only cosmetic ones. On our server everyone spawns with the officer fatigues (green camo), a belt and a cap (green camo).

The idea is simple: A menu that pops up every time a player spawns that allows him to choose between a given set of UNIFORMS, VESTS and HEADGEAR (one, two or all three of these item categories, at the Admin's discretion). The catch is that server admins should only allow a player to choose between UNARMORED gear in this menu, thus NOT PROVIDING any gameplay advantage. Vests should also have the same carrying capacity as the standard belt the server provides.

One could, for example, respawn with civilian clothing, a fedora and some harness.

To make it work every subscriber should just send his player ID to the Admin, who then informs the server through some command that this player is a donor, subscriber, VIP or whatever.

Could this work?

**Comment by AgentRev** [comment]
I don't implement that kinda stuff, that's the server admin's job. Some have already done it with varying degrees of success.

**Comment by Zer01BR** [comment]
I thought that might be the case. But don't you agree that by having this kind of feature as part of the mission itself, free of bugs and complications, would allow servers to monetize more easily and, thus, lead to more servers hosting the mission? I don't know if having more servers *is* your intention, but if it is you should consider it.

**Comment by LouDnl** [comment]
Search for supporter: https://github.com/LouDnl/ArmA3_Wasteland.Altis

**Comment by AgentRev** [comment]
> having more servers

Are you serious? IMHO there are actually too many.

**Comment by osuapoc** [comment]
Making a integrated function for monetizing is just asking for more loving attention of BIS for violation of terms. 

-----Original Message-----

**Comment by AgentRev** [comment]
Also, the monetization policy expires in 3 months, after which Bohemia will evaluate to see if it's viable in the long term.
