### ISSUE TITLE
Server rules not working

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#365]
serverRules.sqf is there was working for a long time noticed it missing after the last update. still missing. getting sad because most people are dumb and I have no list of rules for them to follow...

**Comment by AgentRev** [comment]
You can try changing [this line](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/fca8a0d7ab0b9acea78fdfda1347f0e2caf07cf8/server/init.sqf#L74) to:

    [[call compile preprocessFileLineNumbers (externalConfigFolder + "\serverRules.sqf")], "client\functions\defineServerRules.sqf"] remoteExec ["BIS_fnc_execVM", 0, true];

I have not tried it yet but I believe it might do the trick

**Comment by hobart666** [comment]
thank you , I'll try that now.
