### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#369]
Not sure whats causing this, the first time it happened about 25 bluefor went hvt. so I pulled out the hvt temporarily and looked at the rpt. so it happens again about 24 hours or so later and I check the rpt and find this along with a lot more, any help is greatly appreciated I can upload the .rpt somewhere if it helps.

 (just a portion):
  extDB2 (.\extDB2.dll) [64.0.0.0] [64.0.0.0]
Distribution: 0
Version 1.54.133741
Fault time: 2016/01/10 17:36:41
Fault address:  71FAF237 01:0000E237 C:\Games\ArmA3\A3Master\extDB2.dll
file:     A3Wasteland_v1.2 (__cur_mp)
world:    Altis
Prev. code bytes: 83 E2 FE 8B 5C 24 14 0B D1 8D 4C 24 18 89 57 08
Fault code bytes: 89 33 89 38 3B D9 75 0A 8B 0B 8B 5C 24 10 89 0B

Registers:
EAX:6373DEC0 EBX:00000000
ECX:6373DEC8 EDX:60402BC0
ESI:60402BBC EDI:8B400000
CS:EIP:0023:71FAF237
SS:ESP:002B:6373DEB0  EBP:60402BC0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010206
=======================================================
error: Minidump is unavailable. Cannot create minidump file C:\Games\ArmA3\A3Master\TADST\default\arma3server_2016-01-10_12-25-59.mdmp (error 0x20)
Server: Object 2:12489 not found (message Type_119)
Protocol bin\config.bin/RadioProtocolGRE/: Missing word veh_car

**Comment by AgentRev** [comment]
RPT is irrelevant, extDB logs are.

**Comment by hobart666** [comment]
I have those, where would you like em?

**Comment by AgentRev** [comment]
Doesn't matter.

**Comment by hobart666** [comment]
[18-26-53.log.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/85255/18-26-53.log.txt)
I added .txt that's from tonight.

**Comment by hobart666** [comment]
[17-09-23.log.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/85257/17-09-23.log.txt)
And from last night.

**Comment by AgentRev** [comment]
Doesn't show anything, sorry...

**Comment by hobart666** [comment]
odd, I wonder if its a buggy debug .dll file random the .rpt has alot of oddities in it from that error.
[arma3server_2016-01-10_12-25-59.rpt.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/85258/arma3server_2016-01-10_12-25-59.rpt.txt)
For giggles.
