### ISSUE TITLE
Questions About Config's

### ISSUE THREAD

**Issue by ryan1161** [A3Wasteland/ArmA3_Wasteland.Altis#370]
I was wondering if there is a option to mark player with more than $100,000 on them so that way it forces them to deposit more. Another question is when I play on the map the missions all head to the coast before despairing or is that a timer that runs on them. Last one is there a script that can have the map clean up or restart the server at a certain time of day?

**Comment by AgentRev** [comment]
There is no "option", what you are asking you is a new feature. Server restart is handled outside of the mission system.

**Comment by ryan1161** [comment]
Okay so yesterday when I was hosting like 4 players got in my server and were hacking and the anti-hack was not picking up there hacks they were teleporting and spawning stuff like crazy is there a better anti-hack?

**Comment by AgentRev** [comment]
My antihack does not detect teleporting or item / money spawning. There is the paid infiSTAR antihack which does some of that, but is very hard to setup and I don't provide support for it.

**Comment by ryan1161** [comment]
Okay well I have infiSTAR didn't know it was an anti-hack I will be setting that up then. Thanks

**Comment by AgentRev** [comment]
lol
