### ISSUE TITLE
Server objects all of a sudden not loading

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#371]
Hi, I'm getting this error all of a sudden, I've found in my .rpt `if ((_queryResult select 0) isEqualTo 0) exit>
  Error position: <_queryResult select 0) isEqualTo 0) exit>
  Error Undefined variable in expression: _queryresult
File mpmissions\__cur_mp.Altis\persistence\server\setup\extDB\async_database.sqf, line 63
Error in expression <

_objects pushBack _objData;
} forEach _result;

_objects>
  Error position: <_result;

_objects>
  Error Undefined variable in expression: _result>`  and objects aren't loading from the db everything else seems to be loading from there however.
[21-05-17.log.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/129367/21-05-17.log.txt)
[arma3server_2016-02-13_15-04-32.rpt.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/129368/arma3server_2016-02-13_15-04-32.rpt.txt)

**Comment by AgentRev** [comment]
1. Error is caused by corrupted data caused by unofficial edits
2. Please set `timeStampFormat = "full";` in your server.cfg otherwise I will no longer read RPTs you send me

**Comment by hobart666** [comment]
OK  will do and noted.
