### ISSUE TITLE
Uniforms and/or vests disappear if character is loaded

### ISSUE THREAD

**Issue by wiking-at** [A3Wasteland/ArmA3_Wasteland.Altis#377]
There is an annoying engine bug in arma since 1.54. The uniforms and/or vests keep disappearing in an multiplayer environment. This is especially bad if you loot the equipment of a killed player. It can also happen during normal gameplay without looting.

For the player himself it looks like if he is still wearing the uniform. For the server and other players the uniform is missing. The vest also stops protecting the player although the player himself can see him wearing it.

If the server is running persistence he saves the player without the items. on the next login the player notices that his uniform and/or vest has disappeared with all items stored in it.

This bug is plaging all kinds of multiplayer gamemodes like koth, exile, ...

as the feedback tracker is down you can google for a google cache entry:
0026868: Uniforms disappear or are only visible to one player

As a workaround  a fix could be created which syncs what the client sees with the server and take appropriate action if the bug occured.

attached you find a pbo with a scripting workaround for another gamemode. maybe a similar workaround can be implemented until bohemia fixes this bug.

**Comment by wiking-at** [comment]
[fn_preInit.sqf.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/181292/fn_preInit.sqf.txt)
[config.cpp.txt](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/files/181293/config.cpp.txt)

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/5fef34f824bc04754eb73affc14fe82d054245e6
