### ISSUE TITLE
pve

### ISSUE THREAD

**Issue by deaeye** [A3Wasteland/ArmA3_Wasteland.Altis#378]
hello pls make this server only pve i can't find same like that..

**Comment by AgentRev** [comment]
wat

**Comment by deaeye** [comment]
Ik draaide het interieur is pve alleen...

**Comment by AgentRev** [comment]
English only.

**Comment by deaeye** [comment]
what is not understood by what I wrote?

**Comment by AgentRev** [comment]
Well, for one, we don't host servers, and secondly, your request is very vague.

**Comment by deaeye** [comment]
this server is yours? ''178.32.213.119:2312'' a3 wasteland altis\high fps\hosted by xwedserver.eu 
i mean turn on pve only because i cant find another one pve...now you understood?

**Comment by AgentRev** [comment]
We (A3Wasteland development team) do not host any servers. Other people download A3Wasteland, and host it on their servers. You must contact them, and not us, for such requests... now you understood?

**Comment by deaeye** [comment]
yes ok
