### ISSUE TITLE
Unlimited missiles/rockets

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#379]
When a Taru ammo is attached to an AA tank and when an ammo truck is lifted by an attack helicopter, they can have unlimited missiles/ rockets. This greatly ruins the gameplay. Is there a way to fix this?

**Comment by AgentRev** [comment]
Well, trucks are not liftable by helicopters in my version. The only solution is to make ammo vehicles non-towable / liftable, or remove them altogether like TOP did and add Supply Truck locations with a sequential reload process.
