### ISSUE TITLE
Eden Upgraded

### ISSUE THREAD

**Issue by Spackler** [A3Wasteland/ArmA3_Wasteland.Altis#380]
Has the vanilla been upgraded to compatible with Eden or do I need to follow the steps on the forum?

**Comment by AgentRev** [comment]
Yes, it has been converted in the dev branch, but not in the PBO release.

I also wrote a guide for those looking to convert it manually: http://forums.a3wasteland.com/index.php?topic=2505.0

**Comment by Spackler** [comment]
Thank you..I was following the guide and was like wait a minute this looks like it has, but wanted to make sure. Thank you as always.

**Comment by AgentRev** [comment]
Yeah, I just edited the guide to mention vanilla is already converted. The guide is for people who have made a lot of edits to the mission which would make it harder for them to start over.
