### ISSUE TITLE
Banned in Altis for glitching. Never glitched before. @ADMINS Help please!

### ISSUE THREAD

**Issue by iOwlzy** [A3Wasteland/ArmA3_Wasteland.Altis#382]
Got on Arma and went to the only sever i ever play, "Altis Wasteland" And it said i was perm banned for glitching. Never have attemped glitching in this sever. @AgentRev @Admins please help! In game name is Owlzy.

**Comment by AgentRev** [comment]
http://forums.a3wasteland.com/index.php?topic=2579.0
