### ISSUE TITLE
1.58 broke FAR death messages 

### ISSUE THREAD

**Issue by codexGW** [A3Wasteland/ArmA3_Wasteland.Altis#387]
The death messages are broken in 1.58. We tried deathMessages=0,1,2 on the new 1.58 profile settings, none of them worked. I'll do some more testing later and try to find the issue.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/4b8d59975dac1aaac9f0ae5c81112a4b842f0fcd#commitcomment-17202164
