### ISSUE TITLE
RPT log spam

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#388]
Since a few updates ago, the following message has been in almost every single rpt log of my server.

`11:40:07 Server: Object info 2:4256 not found.
11:40:07 Can't change owner from 0 to 2
11:40:07 Server: Object info 2:4258 not found.
11:40:07 Can't change owner from 0 to 2
11:40:07 Server: Object info 2:4256 not found.
11:40:07 Can't change owner from 0 to 2`

After the 1.58 update, these two lines are generated at least 20 times per second. Any ideas what causes this?

**Comment by AgentRev** [comment]
No, I don't know. Please don't report "RPT spam" to me, because it's never related to A3Wasteland, go on the Bohemia forums.
