### ISSUE TITLE
Treat Yourself and Heal Yourself

### ISSUE THREAD

**Issue by Spackler** [A3Wasteland/ArmA3_Wasteland.Altis#389]
I noticed if you us the heal yourself or treat yourself after standing in fire and getting the red blur around your screen it will take you to 100% but not removed the red blur.

**Comment by AgentRev** [comment]
"Treat yourself" and fire damage are not managed by A3W, it's pure vanilla.

Fire damage in Arma is real messed up: https://www.youtube.com/watch?v=Qbl_xZhO7vs

The "global damage" in that vid is what's used for the HP value.

**Comment by AgentRev** [comment]
I just tested with a campfire in the editor, I see what you mean. It should be disappearing even if not healed, it's definitely an Arma bug.

**Comment by Spackler** [comment]
Sounds good...thank you.

**Comment by AgentRev** [comment]
It is possible to reset the borders by calling `BIS_HitCC ppEffectEnable false;`

**Comment by Spackler** [comment]
Ok I am getting better but any ideas where that would go? Also I shot you a message from the forum. Thank for all your help.

**Comment by AgentRev** [comment]
I don't know about the headless client, sorry.

**Comment by AgentRev** [comment]
I reported the issue on the forums, and BIS said they will look at it.
