### ISSUE TITLE
Rockets

### ISSUE THREAD

**Issue by HAVOCWIZARD** [A3Wasteland/ArmA3_Wasteland.Altis#390]
Hey guys.

Not sure if its just me, but i have picked up that the rockets don't work, okay haven't check everyone but i have a titan on my body and can't sure it. i have tested with another mission file and it looks like its arma itself and not the mission file, anybody else seen this.

Thanks

**Comment by AgentRev** [comment]
> rockets don't work

Could you be more precise?

**Comment by HAVOCWIZARD** [comment]
Sorry rev. the titan launchers don't work it doesn't show in the player menu to use it if you have bought it. i had one strapped on my back from my last saved game and when i go on the player menu it doesn't show to select it, if i remember correctly i last used it before the patch..i have tested with loud's mission and your updated one, but it doesn't show in the menu "player" to select. don't think the problem is from the mission files. my mission file i used is loud's one and i didn't test everything afterwards, i am now busy rewriting the stuff i need from loud's mission into yours. You always update yours and it runs smoother with better frames, Thanks for the hard work i really appreciate it.

**Comment by AgentRev** [comment]
Go in Configure > Controls > Weapons. If you have a button mapped to "Switch to Secondary Weapon", it won't show in the action menu. This was mentioned like 57 times in the Arma SITREPs.

**Comment by HAVOCWIZARD** [comment]
Thanks Rev, I should start reading it then lol.
