### ISSUE TITLE
Laser Designator Batteries disappear

### ISSUE THREAD

**Issue by mooneymoon** [A3Wasteland/ArmA3_Wasteland.Altis#392]
Players can purchase a laser designator from the store and it will have batteries. Logging out will remove the batteries from the designator.

https://community.bistudio.com/wiki/Arma_3_CfgMagazines#Laserbatteries

**Comment by AgentRev** [comment]
This is a sock problem specific to A3Armory. All notions of laser batteries have been removed in the vanilla mission; they are added automatically on login and on purchase.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/a6e87b06e80e107b9a57b2d2ae92813cfdafeaca/persistence/client/players/applyPlayerData.sqf#L137
