### ISSUE TITLE
Abandoned quadrotor cleanup won't work

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#394]
[this commit](https://github.com/Jermin/ArmA3_Wasteland.Altis/commit/438f89752d368a8fd7f8102ff80aa7191bd16316) won't work.

If a player disconnects from the server with a quadrotor connected, the map icon of the quadrotor will turn white and nobody will be able to connect to it (A3W_uavControl set to group). The quadrotor will stay in the air until it runs out of fuel.

**Comment by AgentRev** [comment]
The point of this commit is to delete copters that _are_ out of fuel... Say, if a player's computer has a BSOD, and he reconnects 10 mins later, he would expect his copter to still be where he left it.

**Comment by Jermin** [comment]
OK. Thanks for the explanation.
