### ISSUE TITLE
CfgRemoteExec_fnc.hpp

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#395]
Hi Rev

Can you confirm that this is correct 
`class A3W_fnc_updateSpawnTimestamp { allowedTargets = 2; };`

as i'm getting the following error 

`13:59:52 "Player connected: Mike Hunt [False] (76561198192174931)"
13:59:52 Error in expression <hen
{
[_spawnTimestamps, diag_tickTime] remoteExec ["A3W_fnc_setSpawnTimestamps">
13:59:52   Error position: <remoteExec ["A3W_fnc_setSpawnTimestamps">
13:59:52   Error Type Bool, expected Number, Side, Object, Group, String
13:59:52 File mpmissions\__cur_mp.stratis\server\functions\fn_onPlayerConnected.sqf, line 18`

**Comment by AgentRev** [comment]
The first line has nothing to do with the error. Personally I've never seen it, but it means an incorrect input array is passed to `fn_onPlayerConnected`

**Comment by ghost** [comment]
ok thank you. Where would be the best place to look? i'm using your latest commits.

**Comment by AgentRev** [comment]
What I mean is that this is not supposed to happen in the vanilla mission, it has to be an edit on your end, unless BIS messed up the `PlayerConnected` event. This is the only place where the function is called: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/243b9196f01164b3af7591faa8f3af5f195d5b2a/server/init.sqf#L151

**Comment by ghost** [comment]
i probably need to add that this doesn't happen to all players, maybe 10 to 15 times in 4 hours on a full server. 

i'm sat looking now at the server/init comparing yours and mine and there is nothing obvious so far.

**Comment by AgentRev** [comment]
Oops, sorry, looks like I was wrong: https://community.bistudio.com/wiki/Arma_3:_Event_Handlers/addMissionEventHandler#PlayerConnected

I inverted `_owner` and `_jip`...

**Comment by ghost** [comment]
ah, thanks for taking the time to look, and a big thanks for all that you do !
