### ISSUE TITLE
Undefined variable in expression: a3w_fnc_getteammarkercolor

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#398]
After merging [this commit](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/899aec06f663d4e7a660110f45f95d443dd8a611), the territory marker colors are not working correctly in my server. And I got following errors in the log:

`2339 15:52:35 Error in expression <aptureColor = [_captureTeam, true] call A3W_fnc_getTeamMarkerColor;
2340
2341 if (typeNam>
2342 15:52:35   Error position: <A3W_fnc_getTeamMarkerColor;
2343
2344 if (typeNam>
2345 15:52:35   Error Undefined variable in expression: a3w_fnc_getteammarkercolor
2346 15:52:35 File mpmissions\__cur_mp.Altis\territory\server\monitorTerritories.sqf, line 153
2347 15:52:35 Error in expression <ewMarkerColor = [_newDominantTeam] call A3W_fnc_getTeamMarkerColor;
2348
2349
2350 _currentTe>
2351 15:52:35   Error position: <A3W_fnc_getTeamMarkerColor;
2352
2353
2354 _currentTe>
2355 15:52:35   Error Undefined variable in expression: a3w_fnc_getteammarkercolor
2356 15:52:35 File mpmissions\__cur_mp.Altis\territory\server\monitorTerritories.sqf, line 477
`

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/86b6116587abef465c100ba94c7f17983f69e8b9
