### ISSUE TITLE
Help to install A3Wasteland in my Arma 3 server

### ISSUE THREAD

**Issue by celow** [A3Wasteland/ArmA3_Wasteland.Altis#399]
Hello guys,

I need help, I do not know how to install A3WASTLAND in my Arma 3 server (Havoc).

HELP ME!!

**Comment by ghost** [comment]
you need to read the forum http://forums.a3wasteland.com/index.php?board=2.0

also google it and find many guides out there. https://community.bistudio.com/wiki/Arma_3_Dedicated_Server

**Comment by HAVOCWIZARD** [comment]
Hey Celow, did you come right with this ? let me know, maybe i can help somewhere.
