### ISSUE TITLE
1.60 Respawn / Description error

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#401]
players now get the following error when respawning 

`'mpmissions\__CUR_MP.Stratis\description.ext/RespawnSelectionDialog/Controls/RspnLocMap.LineMarker'.`

i can't find any Bohemia reference to a change to the description.ext following the update

**Comment by AgentRev** [comment]
did 1.60 get released?

**Comment by ghost** [comment]
yes all 3gigs worth !

**Comment by AgentRev** [comment]
Alright, I'll check that later today

**Comment by ghost** [comment]
nice one, 

people are also reporting other issues with reviving team mates but i haven't had chance to replicate it and grab you some rpts as yet
