### ISSUE TITLE
1.60 Line Drawing

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#402]
anyone can now draw lines on the map which you can imagine how bad that gets, 

i noticed killzone kid had posted this fix `findDisplay 12 displayCtrl 51 ctrlAddEventHandler ["KeyDown", {_this select 1 == 29}];`

after reading this thread https://forums.bistudio.com/topic/190676-line-drawing/page-3

**Comment by AgentRev** [comment]
Indeed.

![lol](http://i1190.photobucket.com/albums/z441/misc5551212/20160531024446_1_zpsmezljwg8.jpg)

**Comment by codexGW** [comment]
Agent if you do add a fix maybe add it to the admin uid filter as well. So
admins and in our case maybe community supporters can use it.

**Comment by mooneymoon** [comment]
I wouldn't even be mad if those drawings were all that people are doing. It's the scribble that kills me.

**Comment by AgentRev** [comment]
for now you can put this shit devised by KK in `A3Wasteland_settings\init.sqf` :

```
(createTrigger ["EmptyDetector", [0,0,0]]) setTriggerStatements
[
    "!triggerActivated thisTrigger", 
    "thisTrigger setTriggerTimeout [5,5,5,false]",
    "{if (markerShape _x == 'POLYLINE') then {deleteMarker _x}} forEach allMapMarkers"
];
```

auto-deletes all lines every 5 sec

**Comment by JoSchaap** [comment]
Oh wow.. when you think you've seen it all..

**Comment by Spackler** [comment]
Works if I add it to my mission init but not my A3Wasteland_settings one

**Comment by AgentRev** [comment]
filePatching on?

**Comment by Spackler** [comment]
Yes in config and on server startup line, but does not seem to work. I must be doing something wrong.

`
execVM (externalConfigFolder + "\bannedNames.sqf");
(createTrigger ["EmptyDetector", [0,0,0]]) setTriggerStatements
[
    "!triggerActivated thisTrigger", 
    "thisTrigger setTriggerTimeout [5,5,5,false]",
    "{if (markerShape _x == 'POLYLINE') then {deleteMarker _x}} forEach allMapMarkers"
];`

Here is my crazy startup
`start "arma3" /realtime /affinity FF "arma3server.exe" -port=2502 -filePatching "-config=C:\A3Wasteland\config.cfg" "-cfg=C:\\A3Wasteland\basic.cfg" "-profiles=C:\A3Wasteland" -name=SC "-bepath=C:\BattlEye" -autoInit
`

**Comment by hobart666** [comment]
That's some great art! So this is why it took BIS this many years to get us bipods?

**Comment by hobart666** [comment]
btw KillzoneKid posted this later on https://forums.bistudio.com/topic/190676-line-drawing/?p=3032331

`createTrigger ["EmptyDetector", [0,0,0], false] 
setTriggerStatements [
    "!triggerActivated thisTrigger", 
    "thisTrigger setTriggerTimeout [30,30,30,false]",
    "{if (markerShape _x == 'POLYLINE') then {deleteMarker _x}} forEach allMapMarkers"
];`

He said this "Not really, apparently dedicated can only monitor global channel. In this case put this in mission init.sqf:
This will remove hand drawn markers from all channels every 30 seconds" When someone asked "Is there a way to make a dedicated server aware of more channels? " Since MP only monitors global?

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/752abe4c0519b5b8c8a10a504717ff858020420d

**Comment by nerdalertdk** [comment]
in RC you can disable line by adding 

```
drawingInMap = 0;
```

in your DifficultyPresets

source: https://forums.bistudio.com/topic/183855-release-candidate-branch-announcements/?p=3043571

**Comment by AgentRev** [comment]
Not difficulties, but directly in server.cfg

**Comment by mooneymoon** [comment]
I really like the feature, I just don't like it in global. Can we just do that for global and side chat and leave it for all others?

**Comment by AgentRev** [comment]
Currently no way to detect / control individual channels.
