### ISSUE TITLE
Missing extDB2.dll for A3 Wasteland

### ISSUE THREAD

**Issue by Fallen-Donkey** [A3Wasteland/ArmA3_Wasteland.Altis#405]
Hi team - When ever i start up my server and a player connects up i get the following error?
"[INFO] ███ extDB2 NOT FOUND! Make sure extDB2.dll (Windows) or extDB2.so (Linux) and extdb-conf.ini are in the same directory as arma3server, and that you are using the -filePatching parameter"

I couldnt fid it in the SQL files, is this required and if so where do i get it from?

**Comment by Soloknight** [comment]
https://github.com/A3Wasteland/Release_Files/blob/master/A3W_extDB_pack.zip

just use the .dll file, most of the other files like in the a3wasteland_setting have had slight adjustments 

If you need help with this, reach out and I'll send you my discord info and help you.

**Comment by Fallen-Donkey** [comment]
Thanks Solo! Will do! 

On another note Im not sure about who to contact for this, But i Am trying to skip the briefing page after the lobby. We are currently trying to work off KK's script however with my limited knowledge of scripting i am unable to get it to work. Do you know of an easy way or someone I can contact to get this done?

**Comment by AgentRev** [comment]
You do know the briefing page only shows up on server start right? Anybody who joins afterwards goes straight to spawn

**Comment by Fallen-Donkey** [comment]
Yes, however we are wanting the server to move through the briefing screen before everyone pushes continue - otherwise it can hold up the server for a good period of time while people load.

BTW AgentRev - love your work man!

**Comment by AgentRev** [comment]
Just a thought; try putting KK's code directly in `client\preInit.sqf`

and `briefing = 0;` in `description.ext`

**Comment by Fallen-Donkey** [comment]
Will give that a go, sorry im probably being a major noob here (im still learning alot) do we need to create the preInit.sqf under client\ and call it? if so how would i go about that?

**Comment by AgentRev** [comment]
no the file is already there, copy-n-paste KK's code inside

**Comment by Fallen-Donkey** [comment]
I dont have that file? and ive checked my unchanged .pbo as well :-/

**Comment by AgentRev** [comment]
if you downloaded the PBO you're doing it wrong. you're supposed to download the source code from GitHub and compile the PBO via Addon Builder from the Arma 3 Tools.

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/dev/client/preInit.sqf

**Comment by Fallen-Donkey** [comment]
That would explain alot - my bad give me a bit and we will see how this goes

**Comment by Fallen-Donkey** [comment]
Hi AgentRev, Sorry i working on the wasteland PBO off https://github.com/A3Wasteland/Release_Files. This PBO doesnt have the preinit.sqf in it.

My apologies in posting on the wrong forum

**Comment by AgentRev** [comment]
yes throw it in the garbage and compile from source

**Comment by Fallen-Donkey** [comment]
Thanks Man will do!

**Comment by AgentRev** [comment]
here I added the code: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/099e2fdbd3c61a0d4da511d8c35403e2293290e1

**Comment by Fallen-Donkey** [comment]
Thanks Man! - ill add that in as soon as i can pack this PBO :-D

**Comment by Fallen-Donkey** [comment]
Sorry for being a pain, with the arma 3 addon builder and your source files, Do we package and Binarize and Binarize textures? or just package?

**Comment by codexGW** [comment]
http://www.armaholic.com/page.php?id=16369 This should work.

Edit: Didn't read your comment well. I was a bit tired. You should put all the files in the [zip](https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/archive/dev.zip) to make the pbo. That program I suggested is pretty easy to use.
