### ISSUE TITLE
Been getting this error in the logs with the new UAV Side changes

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Altis#413]
10:59:31 "[Display #24]"
10:59:32 Error in expression <
case "uavSide": { _uavSide = _val call _strToSide };
};

_veh setVariable [_var>
10:59:32   Error position: <_strToSide };
};

_veh setVariable [_var>
10:59:32   Error Undefined variable in expression: _strtoside
10:59:32 File mpmissions__cur_mp.Stratis\persistence\server\world\vLoad.sqf, line 62
10:59:32 Error in expression <select 2) max 500);
};

[_veh, _flying, _uavSide] spawn
{
params ["_uav", "_flyi>
10:59:32   Error position: <_uavSide] spawn
{
params ["_uav", "_flyi>
10:59:32   Error Undefined variable in expression: _uavside
10:59:32 File mpmissions__cur_mp.Stratis\persistence\server\world\vLoad.sqf, line 84
10:59:32 Error in expression <{_grp = group _uav; !isNull _grp};

if (_uavSide != sideUnknown && side _uav != >
10:59:32   Error position: <_uavSide != sideUnknown && side _uav != >
10:59:32   Error Undefined variable in expression: _uavside
10:59:32 File mpmissions__cur_mp.Stratis\persistence\server\world\vLoad.sqf, line 91
10:59:32 "A3Wasteland - world persistence loaded 124 vehicles from extDB"
10:59:42 Unaccessible

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/ee3022c4b28c5ab3c76ed52ba821af60bc88c85a
