### ISSUE TITLE
Repair as Enginner doenst work

### ISSUE THREAD

**Issue by DerSeb90** [A3Wasteland/ArmA3_Wasteland.Altis#414]
Hi,
When im Engineer the Scroll Menu Point "Repair Vehicle" with the Image only appers when i have an Repair Kit. But as Engineer i should be always there? I Have the Tools Kit in my Inventory. Version 1.2b

**Comment by AgentRev** [comment]
The repair kit and the toolkit are 2 different things. The white repair kit is a Wasteland-specific one-time-use item that allows you to repair any vehicle to full health. The black toolkit is an Arma item that allows engineers to repair any vehicle to 50% health.

Now that you mention it, maybe I should indeed make the Wasteland repair option always show when you have an Arma toolkit.

**Comment by DerSeb90** [comment]
Okay that would bei good! Because the engineer is in this case useless... Because now i take medic and buy repair Kits an got the same Things

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/34f7b0ae2e958e080fc5449a95f99295c34d3c05
