### ISSUE TITLE
Request: Independent players only able to see red triangles over their own groups mines...

### ISSUE THREAD

**Issue by usszulu2** [A3Wasteland/ArmA3_Wasteland.Altis#418]
Hi everyone,

I was wondering if there was a way for independent players to be only able to see the red alert triangles over their own groups mines instead of the entire independent "team"? Being able to see every independent mine in an area really reduces their effectiveness. 

Thanks in advance!

**Comment by AgentRev** [comment]
I cannot allow that because it completely defeats the purpose of Arma's mine detector, and I would have to rewrite a new one from scratch. Maybe in the future but not right now.

**Comment by usszulu2** [comment]
Understood. =) Thanks for the quick reply! =)
