### ISSUE TITLE
spawnStoreObject still have setAmmoCargo

### ISSUE THREAD

**Issue by nerdalertdk** [A3Wasteland/ArmA3_Wasteland.Altis#420]
Hi AgentRev

Just notice that you still  use setAmmoCargo in spawnStoreObject.sqf, don't that "break" the intentions of  setupResupplyTruck ?

**Comment by AgentRev** [comment]
ah crap I forgot to remove...

**Comment by nerdalertdk** [comment]
Also had a report that a player could not buy the Taru, (any kind) don't know if thats related, i'm sadly not home to test, but he got the `_showItemSpawnTimeoutError` he could buy an none Taru vehicle

**Comment by AgentRev** [comment]
will look tonight

**Comment by nerdalertdk** [comment]
Just tested and had no problem buying an taru
