### ISSUE TITLE
savePlayerData.sqf, line 16

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#422]
Hey Rev

Have you seen this error before ? i'm my client rpt

`16:27:30 Error in expression <ID = getPlayerUID player;
_manualSave = param [0, false, [false]];

if (!_manua>
16:27:30   Error position: <param [0, false, [false]];

if (!_manua>
16:27:30   Error Type Object, expected Bool
16:27:30 File mpmissions__CUR_MP.stratis\persistence\client\players\savePlayerData.sqf, line 16
16:27:37 Error in expression <ID = getPlayerUID player;
_manualSave = param [0, false, [false]];

if (!_manua>
16:27:37   Error position: <param [0, false, [false]];

if (!_manua>
16:27:37   Error Type Object, expected Bool`

**Comment by AgentRev** [comment]
this cannot have been caused by vanilla code. in theory this would happen should a player save action been added to the action menu, but that was removed years ago.

**Comment by ghost** [comment]
Hmm that's odd the only thing I've recently added was the old non persistent uniform painter. 

Ok thanks
