### ISSUE TITLE
not able to ressuply static weapons

### ISSUE THREAD

**Issue by biabock** [A3Wasteland/ArmA3_Wasteland.Altis#428]
If you try to resupply any static weapon it will say:
"Resuply sequence started / Please get out of the static weapon"
Then after you get out:
"Take back control of the vehicle / Resupply sequence timeout in 30 seconds"
Then after 30 secconds:
"Another player took control of the vehicle / Resupply sequence aborted"

another thing: resupply vehicles are able to repair themselves, this is right?

**Comment by AgentRev** [comment]
> another thing: resupply vehicles are able to repair themselves, this is right?

Well, I knew about it, but I thought meh i'll just leave it there lol.

**Comment by ghost** [comment]
One good side effect is that motors are no longer op :)

**Comment by biabock** [comment]
no doubt this was the best thing from this resupply update xD

**Comment by TheGreatMonkey** [comment]
If you want the original resupply vehicle method comment out lines 80-83 of vehiclesetup.sqf
