### ISSUE TITLE
not able to revive non group players

### ISSUE THREAD

**Issue by biabock** [A3Wasteland/ArmA3_Wasteland.Altis#429]
indie player that isnt at same group are not able to revive each other, have option to revive but not works

**Comment by codexGW** [comment]
Pretty sure that's done on purpose. I guess someone could add a group check to the action for indes. I'm kind of "meh" about it though.

**Comment by AgentRev** [comment]
I don't see a revive option...

![screenshot](http://i.imgur.com/Vr6neOv.png)

**Comment by biabock** [comment]
probably the server that I was playing last days is using a outdated mission, cuz there we had option... since players from my server reported that they cant revive non group players so I thought it was a bug... =D

**Comment by biabock** [comment]
I realized that is really done on purpose... LOL

```
FAR_Check_Revive =
{
    private _target = call FAR_FindTarget;

    **// do not show Revive if target is enemy
    IS_MEDIC(player) && [player, _target] call A3W_fnc_isFriendly && FAR_Check_Dragging**
}
call mf_compile;
```

sorry for this xD

**Comment by AgentRev** [comment]
The purpose is quite simple; people kept reviving enemies by accident... So, yeah.

**Comment by biabock** [comment]
yeah it makes sense...
but the main complaint is after the restart, when before having a group a friend accidentally kills a teammate and isn't able to revive him

**Comment by AgentRev** [comment]
oh, I guess I could add the group management option while in revive
