### ISSUE TITLE
Lock Vehicle Menu Position

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#430]
Hi, 

A few players of ours have been grumbling that the lock action is at the top of the scroll menu and would much prefer it to be at the bottom, 

What do i edit to change this, i'm guessing in Vacations ? 
`//Add vehicle lock action
  _action_id = player addaction [format["<img image='addons\vactions\icons\lock.paa'/> Lock %1", _display_name], {_this call va_lock_action;}, [_player, _vehicle],10,false,false,"",
  format["([objectFromNetId %1, objectFromNetId %2] call va_lock_action_available)", str(netId _player), str(netId _vehicle)]];
  va_inside_actions = va_inside_actions + [_action_id];`

**Comment by biabock** [comment]
I think its done by this 10: _...[_player, _vehicle],**10**,false,false...._

https://community.bistudio.com/wiki/addAction
`priority:
(Optional): Number - Priority value of the action. Actions will be arranged in descending order according to this value. Every game action has a preset priority value. Value can be negative or decimal fraction. Actions with same values will be arranged in order which they were made, newest at the bottom. The bigger the number the higher the action will be positioned on the menu. Typical range is 0 (low priority. Eg: 'Get out') to 6 (high priority. Eg: 'Auto-hover on'). Default value: 1.5`

**Comment by ghost** [comment]
Yes I think your right my old pre apex vacations had this at -5 

Thanks
