### ISSUE TITLE
ayy

### ISSUE THREAD

**Issue by x-bacon** [A3Wasteland/ArmA3_Wasteland.Altis#431]
ayy

**Comment by x-bacon** [comment]
Forgot to mention that if you run the mission locally (as a host) the laser designator works just fine. Also, when i first tried the laser designator in my server it displayed a message like: " Bad vehicle type " but that only happened once and never more. I believe that the code that disables vehicle thermals might be the one causing the issue. Just because, like vehicles there is no black screen nor"thermals offline" and because of this error message that appeared at the exact moment that i switched to laser thermals in my server for the first time.

**Comment by TheGreatMonkey** [comment]
I'm seeing the same problem. I have all thermals enabled on my server. Only laser designators are without thermals.

**Comment by eldrich71** [comment]
same here

**Comment by delevemente** [comment]
Estou com o mesmo problema. No meu servidor local funciona o thermal do Laser, mas quando coloco a missao pra rodar no servidor dedicado ele não funciona. =/
Alguem conseguiu resolver esse problema? Socorro!

**Comment by delevemente** [comment]
I have the same problem. In my local server works the thermal Laser, but when I put the mission to run the dedicated server it does not work. = /
Someone managed to solve this problem? Help!

**Comment by CeccaTTo** [comment]
Same here!!!
