### ISSUE TITLE
Player being wounded when driving through bush in Offroad slowly

### ISSUE THREAD

**Issue by D4n2021** [A3Wasteland/ArmA3_Wasteland.Altis#443]
This is happening on Tanoa, but probably on other maps too?

**Comment by AgentRev** [comment]
the game doesn't allow me to identify what kind of object is being hit. bushes are identified as plain collision damage, so that would be a physics bug with Arma itself and not Wasteland.

**Comment by D4n2021** [comment]
So how can BIA fix it? I tested in vanilla and didn't get wounded testing it...

**Comment by AgentRev** [comment]
They don't even bother replying to any bug report I've filed since the new tracker opened, I have kinda given up hope on them. History shows that bugs tend to worsen over time, maybe one day they'll notice it, but they still won't bother.

**Comment by D4n2021** [comment]
Well there is that "razazel" guy, he replied to all of my bug reports so far (since I started few weeks ago)
