### ISSUE TITLE
Suggestion: Remove boats and light cars/vehicles from aircraft radar

### ISSUE THREAD

**Issue by D4n2021** [A3Wasteland/ArmA3_Wasteland.Altis#444]
Srsly, driving a boat, jet suddenly comes from other side of map (far away) and destroys boats... makes boats a FAR too high risk to use currently... :/ can you please remove boats and also light unarmored vehicles from jet radar? Also decrease jet missile damage vs. tanks/APCs?

**Comment by AgentRev** [comment]
> remove [...] from jet radar

radar is not customizable

> decrease jet missile damage vs. tanks/APCs

![hahaha no](http://i.imgur.com/GvnxtGU.gif)

**Comment by D4n2021** [comment]
Whaaaat that is bad from BIA... :/ maybe remove radar and use custom radar or so?

**Comment by codexGW** [comment]
That would be A LOT of work... a custom radar

**Comment by AgentRev** [comment]
yeah, although the A3 radar is so constantly plagued with bugs that I am starting to comtemplate the idea... if the radar is made in SQF then I can extract and override it, but if it's native code then forget about it
