### ISSUE TITLE
Idea: include the most awesome CUP vehicles in Wasteland!

### ISSUE THREAD

**Issue by D4n2021** [A3Wasteland/ArmA3_Wasteland.Altis#445]
I tested them, would be awesome to include the ones I tested below into wasteland!

https://youtu.be/5rSB5Nc_8mE

**Comment by AgentRev** [comment]
That's a mod, I don't do mods. That's the server owners' job if they want to support mods and get every single one of their players to download and install them properly.

**Comment by ghost** [comment]
I've explained several times Daniel I'm not adding mods or fixing the radar issue or fixing the bushes you've mentioned and all of the reasons why I won't or can't so not sure why you're asking the same questions to get the same answers ?

**Comment by D4n2021** [comment]
I thought maybe AgentRev could do it then you wouldn't have to do it. But ok seems it can only be done by an event in the future (like I wrote in a thread some weeks ago)... :)

**Comment by AgentRev** [comment]
It's really an engine limitation. I would if I could.
