### ISSUE TITLE
UAV Falcon/ Storage Glitch

### ISSUE THREAD

**Issue by KamikaziSpud** [A3Wasteland/ArmA3_Wasteland.Altis#447]
I would like to bring up the glitch concerning the helicopter UAV Falcon vehicle storage glitch. After purchasing the UAV Falcon, and once stored in a Vehicle Storage center, the vehicle is unable to be reconnected to. This is a significant glitch as the chopper is quite pricely, and once parked and retrieved is a useless heap of metal. This is quite concerning as you may not store and later use this vehicle. A solution to this would be very much appreciated and would be beneficial to the gameplay experience of many players.

**Comment by codexGW** [comment]
For some reason the force AI to a team script doesn't work sometimes so the drones will revert back to their original team during a vehicle load (like parking retrieve or restart). In the case of the falcon its blufor. If you went to blufor it would work.

**Comment by ghost** [comment]
I can confirm this does indeed happen
