### ISSUE TITLE
Small Issue 

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#455]
Just to make you aware this no longer works Rev, after the last update. 

// hard CTD if BE kick fails
player setVelocity [0,0,1e38];

**Comment by AgentRev** [comment]
do you want me to ask BIS what is the best way to crash their game?

**Comment by ghost** [comment]
not really a people's person are you. 

I'm not asking you to do anything just letting you know.

**Comment by AgentRev** [comment]
goshdarn it was a joke

I thought there was an `endMission` fallback but I guess I never added it

**Comment by ghost** [comment]
It's hard to tell if your joking sometimes!, 

End mission would be the most logical fallback now I guess until I can find another CTD :-)

**Comment by codexGW** [comment]
Intent or sarcasm is hard to pick up in text, so I try to give most the benefit of the doubt. 

Maybe the best way would make them do a publicVariable that is set to kick in the filters. If you have BEC running with the ScriptBan plugin you can even set that rule to auto ban.

**Comment by AgentRev** [comment]
it already does that, in fact the CTD was a fallback if the pvar kick didn't work

**Comment by codexGW** [comment]
Ok, yeah I thought so. I guess the crashing was just a extra fuck you to the script kiddies.

**Comment by Gigatek1** [comment]
Hmm now I'm curious. Can some one get past the publicVarible or is this just a precaution or for servers without Battleye running?

**Comment by Gigatek1** [comment]
Nm saw the edit just now

**Comment by WhatsUpDoc127** [comment]
Matt what does:



Just to make you aware this no longer works Rev, after the last update.

// hard CTD if BE kick fails
player setVelocity [0,0,1e38];



This do exactly? I am thinking stops a playing from being able to move? Just curious because I like to learn.

**Comment by codexGW** [comment]
Duh, I just saw the "if BE kick fails". Maybe put the pvar on a loop if its prone to fail.

@WhatsUpDoc127 
Its setting the players velocity (looks like up) so fast that it will crash their game or the number is so high that it will crash their game. Here's more info about the command.
https://community.bistudio.com/wiki/setVelocity

**Comment by WhatsUpDoc127** [comment]
Giga yea I knew what setVelocity was but didn't know what it he was saying pertaining to the player, was confused a little. Thanks for the info...
