### ISSUE TITLE
Problems with extra mission

### ISSUE THREAD

**Issue by Lincon13** [A3Wasteland/ArmA3_Wasteland.Altis#456]
Currently, I'm trying to add new extra mission,

As
HackLaptop.
HostileJet.
Smugglers.
Sniper.

When the extra missions are started, they are completed automatically.

The only one that is not automatically completed is the mission, HackLaptop, 
But she did not start with the bot characters.

Can someone show me the way to solve this problem, I'm new to arma3, Sorry

**Comment by AgentRev** [comment]
These custom missions are not part of the A3W core, as such I cannot provide help. Please ask on our [forums](http://forums.a3wasteland.com/index.php?board=7.0), maybe someone will have an answer.

**Comment by WhatsUpDoc127** [comment]
LCBDA I would NOT use the HackLaptop because there is a glitch were more than one person can download the money at the same time. Many servers quit using this mission just because of this glitch...

**Comment by hobart666** [comment]
Mine isn't glitched.

**Comment by WhatsUpDoc127** [comment]
hobart666 did somebody fix the mission because from the forums it was being glitched and most servers disabled it. I know we caught a few who were doing it so we disabled it. You should try it with a couple of people. Again I don't know if the person who created the mission updated it and fixed the glitching issue.

**Comment by WhatsUpDoc127** [comment]
LCBDA are you on Wasteland forums? What is your username I will send you a PM to see if I can help you. I've had a lot of dealings with the mission files switching from 1.2b to 1.3b...

I think it may something in your setupMissionArrays.sqf....So PM on Wasteland forums and I will try to help you.
