### ISSUE TITLE
Update Filters battleye help

### ISSUE THREAD

**Issue by Lincon13** [A3Wasteland/ArmA3_Wasteland.Altis#460]
Hi, first I want to thank you all. Thank you.

Before creating this topic, I searched and did not find the latest updates of the battleye filters.
I'm having problems with the mission failed while trying to get into the server, searching for a forum topic I discovered that could be the battleye filters.

Could someone show me the way to the last battleye filters

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/Release_Files/tree/master/BattlEye

**Comment by Lincon13** [comment]
Thank you AgentRev
