### ISSUE TITLE
Wrong map Loaded

### ISSUE THREAD

**Issue by trevorgolden** [A3Wasteland/ArmA3_Wasteland.Altis#463]
I have tried both Altis and Stratis and both of them are doing this. When I launch the server the map that loads is the new DLC map Tanoa. Has anyone else had this issue. Thanks!

**Comment by WhatsUpDoc127** [comment]
trevorgolden look in your config.cfg thats in your Arma3Config directory. This is what tells your server what map to load. Look for the lines:

//Missions Cycle

in that you should have;
template="A3Wasteland_v1.3b.Altis 

the .Altis is what map is loading so its most likely you are loading .Tanoa...Always look at this first.
