### ISSUE TITLE
New Camo Not loading causing invisible vehicles

### ISSUE THREAD

**Issue by WhatsUpDoc127** [A3Wasteland/ArmA3_Wasteland.Altis#466]
I am adding this as an issue to the issue that was added here:

https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/202

We were having this issue on our new Altis server. I transferred the sql database over using MySqlWorkbench. Then whenever the server started we were seeing vehicles that had the custom textures missing from the vehicles. After much research and reinstalling Arma 3 server I decided to delete all the SavedVehicles rows as our server allows vehicle saving. Once I deleted the rows, I started the server, purchased two tanks with two different custom textures, then about 5 minutes later restart the server and boom it worked. This actually appears to be a extDB and/or mysql database issue. Here is **part** of my report from the line before it showing the missing textures:

`18:03:29 "[extDB2] Sleep [4]: 439.657"
18:03:35 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:35 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:35 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:35 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:35 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:36 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdrylands.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdigi_black.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdigi_black.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdigi_black.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdigi_black.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletexturesdigi_black.paa not found
18:03:37 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:38 Warning Message: Picture clientimagesvehicletextureshex.paa not found
18:03:38 Warning Message: Picture clientimagesvehicletextureshex.paa not found`

What bothers me is 18:03:29 "[extDB2] Sleep [4]: 439.657" because I've never seen this before. Maybe AgentRev can figure this one out. On transferring the database could there have been something that got corrupted?

**Comment by WhatsUpDoc127** [comment]
Okay did some more testing and this is what is happening whenever I use the Schema Transfer Wizard within MYSQL Workbench.

Here is an example of the old database file:

'[["client\images\vehicleTextures\hex.paa",[0]]]'

In the new database file that I copied/transferred it shows this:

'[["clientimagesvehicleTextureshex.paa",[0]]]'

So the \ are being left out. How do I correct this whenever I transfer the schema?

**Comment by AgentRev** [comment]
Obviously this a bug with Workbench and not my stuff, so I can't do anything. Maybe try dumping the data directly into an SQL file and work from there.

**Comment by WhatsUpDoc127** [comment]
Never had this problem before with WorkBench. I even was able to transfer using my local server. But now even on the local server I get the same '[["clientimagesvehicleTextureshex.paa",[0]]]' whenever I transfer the database. I will try some stuff thanks.

**Comment by AgentRev** [comment]
Transferring between servers is not always reliable, minor differences in config can cause MySQL to shit the bed, as some other server owners have learned.

**Comment by WhatsUpDoc127** [comment]
Yep you were correct. I dumped the data and then imported them and boom it works fine now and showing '[["client\images\vehicleTextures\hex.paa",[0]]]'

Thanks for the tip
