### ISSUE TITLE
EnableEnvironment true every second

### ISSUE THREAD

**Issue by wiking-at** [A3Wasteland/ArmA3_Wasteland.Altis#467]
I just changed some stuff in the /client/systems/hud/playerHud.sqf

i saw that in the ui loop every second the following command is set:
enableEnvironment true;
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/dev/client/systems/hud/playerHud.sqf#L355

is there any reason for this or is this command meant to be set outside the loop?

**Comment by AgentRev** [comment]
I put it there out of spite against those pesky environment disablers. Players should not be allowed to mute environment sounds, it is an unfair advantage to everyone who doesn't disable them.

It does not cause any performance gain or loss. This particular issue was resolved by BIS long ago.

**Comment by wiking-at** [comment]
thanks for clarification.
