### ISSUE TITLE
Store NPC bug

### ISSUE THREAD

**Issue by bakednotfried101** [A3Wasteland/ArmA3_Wasteland.Altis#469]
ive been having some troubles with my stores lately, i used to code alot for my old server before it went down and i recently got another server again and i edited it so much and didn't touch the store config but change a few prices and then all the store npcs are wearing civillian clothing and just have blank shop screens and they are displaced a bit without a bench or box. i redownloaded a3w and the only thing i changed was my store config and it broke again after i added all of the cup stuff http://forums.a3wasteland.com/index.php?topic=3269.msg18666#msg18666 if you could help me by checking my store config it would mean alot but everything seems fine to me, unless other people have had this bug before and you know the fix to it...

Thanks

**Comment by AgentRev** [comment]
`-showScriptErrors`

https://community.bistudio.com/wiki/Arma_3_Startup_Parameters#Developer_Options

https://community.bistudio.com/wiki/Crash_Files

**Comment by bakednotfried101** [comment]
so you dont know the fix to it?

**Comment by AgentRev** [comment]
It's called learning how to read RPT logs; you find the first error in your RPT file and fix it, then try again, then rinse and repeat until there are no more errors left.

**Comment by biabock** [comment]
People have serious troubles in knowing the difference between the Issues tab and the forums. lol.

This is not something occurring with the main A3W mission. It's something that you made. By this way, if you can't fix by yourself so you should went to the forum, not here.

**Comment by WhatsUpDoc127** [comment]
AgentRev remember the code we just talked about in your EDITED tutorial? This would most likely fix his issue as I had this same issue. 

bakednotfried101 read this tutorial because how to move or create stores has changed somewhat:

http://forums.a3wasteland.com/index.php?topic=176.0

**Comment by AgentRev** [comment]
That has nothing to do with it.

**Comment by WhatsUpDoc127** [comment]
Sorry I misread it... yea check the storeConfig.sqf you most likely missed a bracket or a comma somewhere. I can help. PM in the forms with the storeConfig.sqf in CODE.

**Comment by bakednotfried101** [comment]
i didnt thoooo
