### ISSUE TITLE
Installing help?

### ISSUE THREAD

**Issue by Twonkk** [A3Wasteland/ArmA3_Wasteland.Altis#473]
Hello everyone.. I have a server running Wasteland Altis 1.2b. I would like to know if this will update my server from 1.2b and if so, how do I update it? as I can't seem to find a .pbo file. Any help would be great.. 

Thanks

**Comment by codexGW** [comment]
Download the zip file from Github, "Clone or download" button. Then make a pbo yourself. This will work
http://www.armaholic.com/page.php?id=16369

Here's the link for the mission files
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/archive/dev.zip

Other than that just google or use the forums search when you have a question. Most have been asked before on the forum. http://forums.a3wasteland.com/

**Comment by Twonkk** [comment]
okay, so i took the copy you posted there, and also the pbo manager, made the pbo, added to the server and it loads but doesnt load the correct map......apparently its a Apex map though the link is Altis......

**Comment by codexGW** [comment]
Make sure the end of the pbo file is .Altis

**Comment by Twonkk** [comment]
ArmA3_Wasteland.Altis-dev.pbo is what i get when i use the pbo manager, should i remove the -dev? so it reads ArmA3_Wasteland.Altis.pbo?

**Comment by codexGW** [comment]
yes

**Comment by Twonkk** [comment]
did that just after i typed.. looks to be working now. :D thanks @Gigatek1  for the help. much appreciated..
