### ISSUE TITLE
1.68 64bit issue

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#474]
Hi Rev, 

I have uncovered an issue i was hoping that you could take a look at please. 

I'm running a local server on the RC branch using 64bit server exe. I have set up extDB3 as per Torn commit here https://github.com/Torndeco/ArmA3_Wasteland.Altis/commit/814637fecbdd5c9035ad347618c071b96c0e9f7a i have not added his later commits for parseSimpleArray. 

i am using your wasteland.ini here https://gist.github.com/AgentRev/4d9c9edc2d3ba0522d8c522f197d22d3 

basically saved/purchased vehicles are NOT deleting from the database when destroyed, my rpt is here although it looks normal http://pastebin.com/5s607qv4

I am also running extDB in debug mode and have the logs for this session here http://pastebin.com/3PLT2GfF

this vehicle will not delete no matter what i do to it in game http://puu.sh/uIQCm/caf0480333.png

i have tried clearing the DB and i still have this issue. 

My mission files are here is that helps? https://github.com/ccgmatt76/CCGStratis

**Comment by AgentRev** [comment]
There are a few remaining issues I need to work out on my end. I guess you can use all of Torndeco's code for now, I think it will work properly.

I just finished my midterms, so I have some free time to ready up an "official" extDB3 version in the coming days.

**Comment by ghost** [comment]
unfortunately that version also has issues with Vehicles now, not sure if BI have pushed something recently that has caused this as initial testing looked fine a few weeks ago :(

**Comment by AgentRev** [comment]
no it has to do with a mistake in my code that extDB2 tolerated but not 3

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/fb9acdcf00997e83d035931b6ece00a150573017

**Comment by ghost** [comment]
i can confirm that using the 'call compile' version and the above fix vehicles are deleting again! 

thank you rev !

**Comment by NinjaJiraiya** [comment]
Extdb3 does not work in linux after the update, I am using version 1027 of extdb3 and v1.68.140908 of arma3, someone with the same problem?
Ps. With the previous version (v1.66.139586) worked normally

**Comment by NinjaJiraiya** [comment]
Solved 

Version v1.68.140940 addresses the issue

**Comment by ghost** [comment]
rev not sure if you have seen the post on the forums but there is an issue with your fork branch not working with parked vehicles. http://forums.a3wasteland.com/index.php?topic=3213.75

**Comment by codexGW** [comment]
> rev not sure if you have seen the post on the forums but there is an issue with your fork branch not working with parked vehicles. http://forums.a3wasteland.com/index.php?topic=3213.75

I reverted this but I'm still getting this error ( same as the one mentioned on the forum topic) for parking load.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/5bf2ab5b469260d4f3ea0446bcacdbaf187dddfe

**Comment by AgentRev** [comment]
I just updated the ini

**Comment by codexGW** [comment]
Works great. No errors or issues with my parked vehicles. There is more then the limit because the save was still working not the load.
