### ISSUE TITLE
Having this error occasionally in the log since 64-Bit

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Altis#475]
21:03:02 Error in expression <f"

if (!isServer) exitWith {};

params [["_unit",objNull,[objNull]], "",>
21:03:02   Error position: <params [["_unit",objNull,[objNull]], "",>
21:03:02   Error Params: Type Bool, expected Array
21:03:02 File mpmissions\__cur_mp.Stratis\server\functions\serverPlayerDied.sqf, line 11

**Comment by ghost** [comment]
And you have this commit ? https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/fb9acdcf00997e83d035931b6ece00a150573017

**Comment by ghost** [comment]
Sorry this one https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/983de3ea96de8c95cdafcb8106f4564a46f488a6

**Comment by Soloknight** [comment]
Thanks had all of them but the public variable

**Comment by Soloknight** [comment]
Actually it still happing even with those changes

**Comment by Soloknight** [comment]
Matt has your been crashing daily?

**Comment by AgentRev** [comment]
Are you even running the right codebase? You must undo all changes initially published by Torndeco and use the new extDB3 branch

**Comment by ghost** [comment]
No crashes this end as Rev says check his Altis fork out and make sure you update fully

**Comment by codexGW** [comment]
We have been running with out any crashes since switching from 32bit to 64bit. Like Agent and Matt said make sure to use the exDB3 branch. Make sure you are using the latest ini and try Arma perf branch. Oh don't forget the disconnect fix in Dwardens dropbox.

A3W ini
https://gist.github.com/AgentRev/4d9c9edc2d3ba0522d8c522f197d22d3

perf branch
https://forums.bistudio.com/forums/topic/160288-arma-3-stable-server-168-performance-binary-feedback/?do=findComment&comment=3167133

Disconnect fix. Put this in your @extDB3\addons folder
https://www.dropbox.com/sh/582opsto4mmr8d8/AAA56EqM2Nd05BdGW_xq1sqFa/168perf/_dedicated_server_disconnect_fix_servermod_only?dl=0

**Comment by nerdalertdk** [comment]
or just use 32 bit :) works fine on my server, waiting til arma64 is not beta anymore

**Comment by codexGW** [comment]
32bit was causing us to crash but that was the default branch not perf. perf would probably fix that. It really went off without a hitch once I installed Agents latest ini. @nerdalertdk What do you mean arma64 beta? 64bit is in the main Arma branch now.

**Comment by nerdalertdk** [comment]
Yeah first version of something bohemia makes is still beta ;) dammn arma still feels like an Beta product

**Comment by codexGW** [comment]
Lol yeah. The perf brach is like their new hotfix/test branch now as well. I haven't noticed any difference in performance using it for quite sometime.

**Comment by WhatsUpDoc127** [comment]
Its addons causing the "Private variable in Global Space"....Its not going to hurt anything. It was fine in 32 bit but something changed in 64 bit has this is the only thing causing the error. Soloknight are you using ScarCode addons which is a server restart warning? In the Dev branch this is where I was getting that same error. Its not going to hurt anything and it will still run. BTW no server crashes here, I use Fire Daemon.

**Comment by Soloknight** [comment]
I'm checking the whole system out, I have totally redid the arma 3 install and have all of Rev updates. In The logs the headless client seem to disconnect and arma crashes

**Comment by ghost** [comment]
Have you tried without a headless client?, I don't use one myself

**Comment by Soloknight** [comment]
I updated to the latest perf branch Thanks, Gigatek and I changed out our ram, seem to be running great
