### ISSUE TITLE
General Store OBJECTS won't spawn

### ISSUE THREAD

**Issue by WhatsUpDoc127** [A3Wasteland/ArmA3_Wasteland.Altis#485]
No Objects at the General Store will spawn now after the 1.3c update. I tested this even with the vanilla release of A3W 1.3c on my test server and I get "Unknown Error Occurred". You can test this out for yourself but I can promise you Objects will not spawn. I thought it I did something wrong on my end until I decided to take A3W Altis Dev and put it up on my test server. Still same result.

**Comment by ghost** [comment]
have you added all of the latest updates ? https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/4b1f73b3f9bb2ea1f417d556bcdf9c5d1c470cea

**Comment by hobart666** [comment]
I'm using a brandy new version of vanilla from the git downloaded yesterday using the mission.sqm rev edited today and this is happening on stratis. And my dl was a bit older than the commit!!! lol

**Comment by WhatsUpDoc127** [comment]
Matt I just downloaded the Altis Dev Build early in the morning around 2am (Wednesday May 17) so unless you guys changed something from 2am to now its a problem.

Like I stated I tested it out with the Vanilla A3W Altis DEV.

**Comment by hobart666** [comment]
Ya that commit works just added it & tested objects spawn faster than you can release the mouse button.

**Comment by WhatsUpDoc127** [comment]
Okay I am testing it out now. WOW just one line that was changed then changed again..LOL It was probably changed right after I downloaded the Dev itself.

**Comment by WhatsUpDoc127** [comment]
HOORAY!!! Yep that was it...I am laughing seriously right now as I checked that file 10 times last night and gave up on it. Thanks for the update.

**Comment by hobart666** [comment]
Hahaha I dig that! I'm near hysterics with a search I've been doing with agent ransack for hours again trying to find something that's very well hidden.
