### ISSUE TITLE
Still cannot purchase general store "objects".

### ISSUE THREAD

**Issue by ArmaSoldiers** [A3Wasteland/ArmA3_Wasteland.Altis#487]
This update: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/4b1f73b3f9bb2ea1f417d556bcdf9c5d1c470cea ...does not work. I think you also need to update buyItems.sqf, no? Because I can see buyVehicle.sqf has changes in it.

Could you please verify this again? This is urgent and been at it for several hours but can't figure out what is wrong.

Thank you.

**Comment by AgentRev** [comment]
everything works very much fine on my end, looks like your codebase is out of sync. You don't "apply updates", you
# MERGE
the whole thing.

**Comment by ArmaSoldiers** [comment]
My bad! It works! Sorry! **Thank you very much!**
