### ISSUE TITLE
VS

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#490]
Hi, 

Not sure what i have done or if its a bug? but the VS has stopped working since this commit https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/19e36cb22b31988a16aaafbfd91fcd954d221d8c

server/functions/spawnStoreObject.sqf

works fine before but now i get 'waiting server responce' and no errors to report.

**Comment by AgentRev** [comment]
What about the server RPT?

**Comment by AgentRev** [comment]
Everything works fine on my dedi, please run a compare between your spawnStoreObject.sqf and the vanilla one to see if there's anything missing.

**Comment by ghost** [comment]
okay thanks, will do

**Comment by ghost** [comment]
omg i know exactly what it is, remember the conversation on the forums about changing a certain variable, seems idiot here updated that file with the vanilla value still in place :(
