### ISSUE TITLE
Carrier VS desk

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#491]
using your latest commits the desk seems to be up in the sky ! ? 

http://puu.sh/w0YXn/0dbc48c5aa.jpg

**Comment by codexGW** [comment]
Me too
![20170525160955_1](https://cloud.githubusercontent.com/assets/9350182/26474282/efd57cde-4164-11e7-91a9-2548704a7be0.jpg)

**Comment by codexGW** [comment]
Never mind went back down after a minute... Weird.
