### ISSUE TITLE
The store does not consider the price for each item when selling

### ISSUE THREAD

**Issue by topden** [A3Wasteland/ArmA3_Wasteland.Altis#493]
Is this a bug or so conceived? If so conceived, then why is the calculation of all items if the price does not match?
http://joxi.ru/zAN6z1WTbORkA9
http://joxi.ru/BA0G5woh0oO52y
http://joxi.ru/MAjBEkqCV7M6Ae
http://joxi.ru/RmzoE6ZH6ZBp2O
http://joxi.ru/v29G3wphEq6drG

This is in all versions and on all islands. And servers. Can this be changed?

**Comment by codexGW** [comment]
Yeah a dev we were working with was commenting on this. Never bothered to test it though.

**Comment by topden** [comment]
And you communicate with Sa-Matra? In his missions it works. Maybe he can help?

**Comment by AgentRev** [comment]
Should be fixed with latest commit.
