### ISSUE TITLE
Any ideas why my A3Wasteland server won't ping?

### ISSUE THREAD

**Issue by jeremylamb2** [A3Wasteland/ArmA3_Wasteland.Altis#494]
I'm running A3Wasteland with TADST on a Vultr dedicated server.
http://pasteo.hosthorde.net:8080/view/3d1feedd
Heres my log... Any ideas why i Cant' ping the server?

**Comment by codexGW** [comment]
Create incoming rules for Windows firewall for arma3server_x64.exe or arma3server.exe. If you are talking about ICMP (ping) you don't need that but just create a ICMPv4 incoming rule to pass all.

**Comment by jeremylamb2** [comment]
I just did that, and I mean i can't ping it in the Arma 3 menu so nobody can join. I have another server for Rust with this host and I didn't have to go through port forwarding so I don't think its that

**Comment by jeremylamb2** [comment]
@Gigatek1

**Comment by codexGW** [comment]
Port forwarding is if you are behind another firewall... Just watch a video on Windows firewall or just turn it off. If it works with it off then you know that's what it was and then maybe you can take the time to learn about it.

**Comment by jeremylamb2** [comment]
@Gigatek1 thanks, its fixed :)
