### ISSUE TITLE
vehicle/heli/building material  wont stop spawning and causing lag ! 

### ISSUE THREAD

**Issue by lima12** [A3Wasteland/ArmA3_Wasteland.Altis#496]
here is the problem !
we using ver 1.7 and the problem is :  
+ vehicle keep spawning and keep spawning w/o stop or cleaning causing lag for server after 5 min 
+ vehicle spawn overlap each other and .... BOOM  !

**Comment by ghost** [comment]
What else have you changed or edited within the mission file ?

**Comment by hobart666** [comment]
:D matt!

**Comment by lima12** [comment]
i fixed the problem ! DO NOT USE THE MAIN_CONFIG ! ! use the default !

**Comment by ghost** [comment]
no you have patched the problem, whatever you have done you have messed something up as vanilla has no issues like that.

**Comment by lima12** [comment]
i have done NOTHING but copy the folder wasteland config in the zip file i download from github to the root server !

**Comment by AgentRev** [comment]
I dunno what you're raving about, there is no version 1.7, latest is v1.3c

**Comment by lima12** [comment]
i mean game version 1.7 not the wasteland 1.7

**Comment by AgentRev** [comment]
It's **1.70**, not _1.7_

**Comment by ghost** [comment]
We are on 1.72 stable now however that shouldn't make a difference to the current wasteland mission so no idea what or why you have problems without more information, why not start by posting your server rpt

**Comment by lima12** [comment]
nevermind ... it a ; errors ! fixed !

2017-06-29 2:52 GMT+07:00 CCGMatt76 <notifications@github.com>:

**Comment by ghost** [comment]
It's always a good idea to share your server rpt when reporting issues, but glad it's fixed
