### ISSUE TITLE
Paking bugs

### ISSUE THREAD

**Issue by Merciful78** [A3Wasteland/ArmA3_Wasteland.Altis#498]
Unable to park Ifrit HMG from mission. ABLE to park static weapons. (this may have always been the case I just have not come across it before.)

**Comment by codexGW** [comment]
Seems to affect all mission vehicles. I can park a town vehicle without saving it but when I bring a mission vehicle to parking it wont show in the park menu, even if I acquire ownership.

Good news statics can be removed in the parking config.

**Comment by codexGW** [comment]
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/2ab43f42bc6ac1984394758369e36e13804d2eeb#diff-ca0d924c700455d9614d6d7eacfd8546R138

This fixed the mission vehicles
