### ISSUE TITLE
MessageSystem errors

### ISSUE THREAD

**Issue by Soloknight** [A3Wasteland/ArmA3_Wasteland.Altis#500]
I keep getting these errors with missions and group invites
11:47:05 "Message Money Objective--------------------------------Medium Money ShipmentA convoy transporting $150,000 escorted by a MSE-3 Marid is en route to an unknown location.Stop them!"
11:47:05 Error in expression <geSystem];

_hint = messageSystem;
hint parseText _hint;
>
11:47:05   Error position: <parseText _hint;
>
11:47:05   Error parsetext: Type Text, expected String
11:47:05 File mpmissions\__CUR_MP.Stratis\client\functions\serverMessage.sqf, line 11

**Comment by ghost** [comment]
Something you've added is parseText it twice,  remove it from the above file and see how you go.

Hint _hint;

**Comment by AgentRev** [comment]
No, it means one of the mission files is broadcasting parsed text, which is wrong. serverMessage is fine.

**Comment by Soloknight** [comment]
Ok got that one fixed but this one still causing issues

18:57:47 Error in expression <functions\fn_encodeText.sqf"









_this splitString "" apply {["&amp;","&lt;","&>
18:57:47   Error position: <splitString "" apply {["&amp;","&lt;","&>
18:57:47   Error splitstring: Type Array, expected String
18:57:47 File mpmissions\__CUR_MP.Stratis\client\functions\fn_encodeText.sqf, line 10

Whenever I send an invite to a player

**Comment by AgentRev** [comment]
Oops, my bad. https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/62c5a59b39c8fcb20f0dc9f8b19fc0f779ed4f54

**Comment by Soloknight** [comment]
Thanks Rev

**Comment by AgentRev** [comment]
Ok I really messed up that function, fixed again; https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/87fac6b74b245f54081230311eee7b0b4def17ae
