### ISSUE TITLE
Last Resort

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#502]
When players are downed they can now look around which is a nice feature however players are now not able to select last resort due to no available cursor, unless i'm missing something ?

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/59f126115a25062d748a5aad7ae19c0a6192481f/addons/far_revive/revive_gui.hpp#L163
