### ISSUE TITLE
Function whitelisting

### ISSUE THREAD

**Issue by clundstrom** [A3Wasteland/ArmA3_Wasteland.Altis#506]
I'm trying to call bis_fnc_arsenal from a custom arsenal function but keep getting kicked by the anti-hack.

I've added 
arsenal to the

filterExecAttempt.sqf
and Cfg_remoteExec_fnc.hpp

and in the clientcompile.sqf i've added 
arsenal  = "arsenal.sqf" call mf_compile;

still no luck. Got any tips?

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/25cd65ffc60b1dfefb9f50c8035cfb747498dcb7/server/antihack/payload.sqf#L111

**Comment by clundstrom** [comment]
Oh wow! there was the little bugger.. Thanks a bunch! It's working flawlessly now.
