### ISSUE TITLE
Money dropped from players when killed would sink into the ground sometimes

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#507]
The object searcher can find it. But we can't see it where it is marked.

**Comment by AgentRev** [comment]
Sounds like an Arma bug that I can't fix.

**Comment by Jermin** [comment]
Weapons can get lost, too, in which case I can't find it in the object searcher.

**Comment by AgentRev** [comment]
That's Arma, can't do anything about that.

**Comment by SanctuaryTactical** [comment]
Money is there, just underground.  Any way we can reposition it to the RIP position when the player dies?
Yes though.  Definitely an Arma bug (As is randomly losing your rifle)

**Comment by AgentRev** [comment]
I have found the problem. For whatever reason, sometimes `getPosATL` will give a negative height for corpses, and `dropPlayerItems` tries to spawn stuff at corpse height, so things would spawn underground. I applied a lower boundary of 0 to the height of `getPosATL` and it seems to have did the trick.

Sadly, I don't think I can prevent lost weapons.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/b23b020e8f323dcc76bc0bb32f7f560896162402
