### ISSUE TITLE
Script oSaveSetup.sqf, line 23 Error, x64, WinSRV

### ISSUE THREAD

**Issue by griha41** [A3Wasteland/ArmA3_Wasteland.Altis#509]
2018/01/17, 22:58:45 Duplicate HitPoint name 'HitGun' in 'C_Van_01_transport_F'
2018/01/17, 22:58:45 Duplicate HitPoint name 'HitTurret' in 'C_Van_01_transport_F'
2018/01/17, 22:58:45 Duplicate HitPoint name 'HitGun' in 'C_Van_01_transport_F'
2018/01/17, 22:59:27 Strange convex component24 in a3\structures_f\households\house_small02\u_house_small_02_v1_dam_f.p3d:geometryView
2018/01/17, 22:59:28 "A3Wasteland - world persistence loaded 1 vehicles from extDB"
2018/01/17, 22:59:34 "A3Wasteland - world persistence loaded 0 mines from extDB"
2018/01/17, 22:59:35 "-- LOOTSPAWNER Buildingpositions_list ready, d: 894.641s"
2018/01/17, 22:59:39 Error in expression <rEach [objectList, essentialsList, call genObjectsArray];

_savingInterval = ([">
2018/01/17, 22:59:39   Error position: <genObjectsArray];

_savingInterval = ([">
2018/01/17, 22:59:39   Error Undefined variable in expression: genobjectsarray
2018/01/17, 22:59:39 File mpmissions\__cur_mp.Altis\persistence\server\world\oSaveSetup.sqf, line 23
2018/01/17, 22:59:42 Error in expression <cts pushBack toLower _obj;
};
} forEach _x;
} forEach [objectList, essentialsLis>
2018/01/17, 22:59:42   Error position: <_x;
} forEach [objectList, essentialsLis>
2018/01/17, 22:59:42   Error Undefined variable in expression: _x
2018/01/17, 22:59:42 File mpmissions\__cur_mp.Altis\persistence\server\world\oSaveSetup.sqf, line 22
2018/01/17, 22:59:48 "WASTELAND - Vehicle spawning completed - 196 town vehicles spawned in 157.865s"
2018/01/17, 22:59:51 "-- LOOTSPAWNER LSusedclass_list ready, d: 15.9039s"
2018/01/17, 22:59:51 "-- LOOTSPAWNER LSDer started..."
2018/01/17, 22:59:58 Duplicate HitPoint name 'HitTurret' in 'O_Boat_Armed_01_hmg_F'
2018/01/17, 22:59:58 Duplicate HitPoint name 'HitGun' in 'O_Boat_Armed_01_hmg_F'
2018/01/17, 22:59:59 Duplicate HitPoint name 'HitTurret' in 'B_Boat_Armed_01_minigun_F'
2018/01/17, 22:59:59 Duplicate HitPoint name 'HitGun' in 'B_Boat_Armed_01_minigun_F'
2018/01/17, 23:00:02 "WASTELAND SERVER - 15 Boats Spawned"
2018/01/17, 23:00:28 "WASTELAND - Object spawning completed - 387 objects spawned"
2018/01/17, 23:00:40 "WASTELAND SERVER - 15 Ammo Caches Spawned"
2018/01/17, 23:00:41 "[INFO] A3W territory capturing is ENABLED"

**Comment by AgentRev** [comment]
Do you have the log file?

**Comment by griha41** [comment]
[https://drive.google.com/file/d/1qMPvnadOGjCjclp_zqroQ1nHaW5EtMkl/view?usp=sharing](url)

**Comment by AgentRev** [comment]
This is a different log, do you have the original one that you referenced earlier?

**Comment by griha41** [comment]
Yes, sorry. Here log from those date, but same script error in same section.
https://drive.google.com/file/d/1mdkwUbOcozXVyItM4BgTTESHU8lPeTiC/view?usp=sharing

**Comment by AgentRev** [comment]
I would need to see your storeConfig.sqf

**Comment by griha41** [comment]
Here it's.

https://drive.google.com/open?id=1JQ1Wy5-spVvITAgrWCTKuQWGVJXVth07

**Comment by AgentRev** [comment]
I can't see the problem at first glance, I'll check back home later tonight.

**Comment by griha41** [comment]
No problem, perhaps it's last Arma update...

**Comment by AgentRev** [comment]
No, I am 99% certain there is a syntax error in storeConfig.sqf, in some cases they don't show up in the RPT log.

**Comment by griha41** [comment]
Nevertheless many thanks for your help and awesome mission.

**Comment by AgentRev** [comment]
Okay, can you send me your full mission? I don't have any errors on my end.

**Comment by griha41** [comment]
Ok, here full mission folder https://drive.google.com/open?id=1UqUqaJ1cUDnUCYk0rgL4csuYq0KXQ2IN

**Comment by AgentRev** [comment]
Server crashes right on startup because `addons\R3F_ARTY_AND_LOG` is empty.

**Comment by griha41** [comment]
see your piont. peraps i need drop a pbo...

**Comment by griha41** [comment]
Please try this one. https://drive.google.com/open?id=1Y9_k10oKQTMsGJSUD7IiLi3aAilaNv0R


I've checked google drive store in folder ther's  files. This link contains a PBO File

**Comment by AgentRev** [comment]
I don't get the server error: https://gist.github.com/AgentRev/a78b3ad357a1eec5e85411dff66c557a

However I get a client error, `client\functions\playerSetupGear.sqf` line 70, it says

    	case default: {

which is incorrect, and instead should be

    	default {

**Comment by griha41** [comment]
strange. Do you use any Debug variables? (in next time to check ut script errors)

**Comment by AgentRev** [comment]
Please define "Debug variables"

**Comment by griha41** [comment]
variables, switches, dump functions which allow you get detailed information about errors.

**Comment by AgentRev** [comment]
No, I put your PBO as is and booted arma3server.

**Comment by AgentRev** [comment]
The arma3server command line says you're using `-netlog` option, are you aware that this slows down everything by a factor of 10?

**Comment by griha41** [comment]
Indeed, the mistake was in the player's startin' loadout. I apologize for taking so much time. With respect to you and your work.
