### ISSUE TITLE
Vehicle sale price

### ISSUE THREAD

**Issue by kbuddle** [A3Wasteland/ArmA3_Wasteland.Altis#518]
Possible issue in code line 68 where checking vehicle type and variants in sellVehicle.sqf. After changes in 1.4D related to vehicle paint, sale price of at least spawned buzzards has reduced to default $1000. Dont understand intent of new code but when i commented out the changes and reverted to original pre last commit, sale of vehicles proceed as per the old 50% chop shop price. Have not tested vehicle resupply or salvage which has same code included. Or do you think there I have another issue at play?

**Comment by AgentRev** [comment]
Intent was because CAS variants of DLC jets were being recognized as AA variants by those scripts, and you are right about the bug... I believe the solution I need to apply is revert to the original code and simply add actual variant flags to the CAS variants in storeConfig.

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/5739418bfbfa6d352ff782bada5b7ad568a20794
