### ISSUE TITLE
you were kicked off the game. (battleye admin kick (vac ban ou game bans na steam não é permitida))

### ISSUE THREAD

**Issue by SCUSSEL11** [A3Wasteland/ArmA3_Wasteland.Altis#527]
não consigo entrar em um servidor do arma 3 por causa disso, como resolvo>

**Comment by hobart666** [comment]
Buy a new copy of the game on a different steam account and don't use
cheats on any game with the new account. The server you tried connecting to
doesn't allow people with vac bans from any game (Once a cheater, always a
cheater.)

Compre uma nova cópia do jogo em uma conta steam diferente e não use
cheats em qualquer jogo com a nova conta. O servidor ao qual você tentou se conectar
não permite pessoas com banimento de vac de nenhum jogo (uma vez trapaceiro, sempre um
trapaceiro.)

**Comment by JoSchaap** [comment]
This is not an issue with a3wasteland
